src/css/components/po-field/po-checkbox-group/po-checkbox-group.css, src/css/components/po-field/po-field-container/po-field-container.css, src/css/components/po-field/po-select/po-select.css
**PO SELECT**
[DTHFUI-1003](http://jiraproducao.totvs.com.br/browse/DTHFUI-1003)
DTHFUI-1258 - po-select - problemas de responsividade em alguns browsers 
**Situação**
O tamanho do select estourava no iPad, sugiro a leitura dos comentários da Issue para complementar a situação.
**Solução**
Adicionado position relative para o pai do elemento e position absolute para o elemento, assim o tamanho do select fica limitado.
**Simulação**
Abrir o sample labs do `po-page-default` no modo mobile, de preferência no iPad e ao utilizar o select visualizar o tamanho dos elementos. 
Importante validar se houve algum efeito colateral nos componentes que utilizam a classe `po-field-container`.
=> po-select/DTHFUI-1003 - problemas de responsividade em alguns browsers

gulpfile.js
**DTHFUI-1293** 
**Situação:**
Repositório do @portinari/style está gerando a pasta com o nome incorreto
**Solução:**
Altera a pasta gerada na distribuição de po-theme para style.
**Simulação:**
Gerar a distribuição utilizando o comando `npm run build` e verificar se a pasta gerada está com o nome "style". Também é importante pegar esta pasta e colocar no `node_modules `do portinari-angular para verificar se o css continua funcionando normalmente.
=> build(gulp): altera a pasta gerada na distribuição de po-theme para style

src/css/components/po-menu/po-menu.css
PO-MENU
DTHFUI-1626
Situação:
Ao definir 12 colunas para um elemento no Menu Header Template, o mesmo não ocupava a largura total.
Solução:
Definida a largura em cem por cento na classe utilizada no Menu Header Template do menu.
Simulação:
```
<po-menu [p-menus]="[{ label: 'Item', link: '/'}]" p-filter>
<ng-template p-menu-header-template>
<po-combo class="po-md-12" name="name" [(ngModel)]="name" [p-options]="[{value: '1', label: '1'}]"> </po-combo>
</ng-template>
</po-menu>
```
=> fix(menu): corrige comportamento do grid system no template

src/css/components/po-table/po-table.css
Ao utilizar o lookup está aparecendo dois scrolls verticais no IE.
Deve aparecer apenas um scroll na tabela e este scroll deve estar no conteúdo.
**Simulação:**
a correção do problema pode ser visto ao utilizar estes componentes no portal.
[PR do portinari-theme](https://totvstfs.visualstudio.com/THF/_git/portinari-theme/pullrequest/14269?_a=overview)
OBS.: importante testar no mobile.
=> fix(table): corrige scroll do eixo y no IE

README.md, gulpfile.js, package.json
Melhoria em relação a documentação para iniciar o desenvolvimento de um tema novo e conseguir validar o esquema de cores.
- Adicionado a dependência de desenvolvimento: http-server;
- Incluído script "dev" no package.json para iniciar o servidor http a partir do diretório de compilação;
- Incrementado a documentação com as informações para build de outros temas;
- Ajustado script gulp para informar o tema que está sendo utilizado (apenas quando watch);
=> Ajuste documentacao desenv

src/css/components/po-toolbar/po-toolbar.html
**PO-TOOLBAR**
**DTHFUI-1936**
***
***
O problema ocorre dada a falta de definição da propriedade `p-profile` tendo a definição de uma `p-profile-actions` definida no mesmo contexto.
Agora o componente permite utilizar a propriedade `p-profile-actions` sem que haja um `p-profile` definido.
**Simulação**
É possível simular o problema removendo a definição de `p-profile` no _sample logged_ do componente.
UI: https://github.com/portinariui/portinari-angular/pull/88
=> fix(toolbar): corrige o funcionamento sem o p-profile

src/css/components/po-upload/po-upload.html
Adicionados samples que exibem inclusão de envio de pastas.
• Os textos dos labels do botão de inclusão alteram conforme as opções para folder ou arquivos;
• Também foram tratados os textos relacionados ao drag and drop conforme a opção;
• Para quando houverem mais de 5 ítens, foi fixado uma altura máxima para geração de scroll assim como encapsulamento no componente `po-container`;
• Se houver uma quantidade menor que 5, prevalece o comportamento atual;
Fixes DTHFUI-787
=> feat(upload): adiciona opção para envio de pastas

src/css/components/po-tag/po-tag.css, src/css/components/po-tag/po-tag.html, src/css/themes/po-theme-default.css
**PO-TAG**
**DTHFUI-1762**
***
***
Agora o componente permite a utilização da paleta de cores além de ícones e navegação através do teclado.
UI: https://github.com/portinariui/portinari-angular/pull/98
=> feat(tag): permitir o uso da paleta de cores e ícones

src/css/components/po-modal/po-modal.css
**PO-MODAL**
**DTHFUI-2060**
***
***
Agora o componente impede a geração de scroll na vertical do seu
conteúdo, corrigindo assim o comportamento nos navegadores
Internet Explorer e Microsoft Edge.
=> fix(modal): corrige scroll ao usar po-url no IE/Edge

src/css/components/po-field/po-lookup/po-lookup.html, src/css/components/po-table/po-table.css, src/css/components/po-table/po-table.html
O seletor po-table-column-checkbox foi renomeado para po-table-column-selectable.
Fixes DTHFUI-2515
**OBS:** Ver PR no `portinari-angular`.
=> refactor(table): renomeado o seletor po-table-column-checkbox

.huskyrc, .travis.yml, package.json
Adiciona Travis ao repositório para validar os commits.
Detalhes das atualizações:
- separa a configuração do husky em um arquivo separado;
- adiciona arquivo de configuração do travis;
- atualiza dependências do commitlint e do husky.
=> build: configuração para validar commits das PRs

.prettierrc, .travis.yml, package.json, src/app/js/app.js, src/css/components/po-field/po-lookup/po-lookup.html, src/css/components/po-field/po-rich-text/po-rich-text.html, src/css/components/po-loading-overlay/po-loading-overlay.html, src/css/components/po-menu/po-menu.html, src/css/components/po-modal/po-modal.html, src/css/components/po-page/po-modal-password-recovery/po-modal-password-recovery.html, src/css/components/po-page/po-page-blocked-user/po-page-blocked-user.html, src/css/components/po-page/po-page-change-password/po-page-change-password.html, src/css/components/po-page/po-page-list/po-dynamic-advanced-filter/po-dynamic-advanced-filter.html, src/css/components/po-page/po-page-login/po-page-login.html, src/css/components/po-popup/po-popup.html, src/css/components/po-progress/po-progress.html, src/css/components/po-slide/po-slide.html, src/css/components/po-stepper/po-stepper.html, src/css/components/po-table/po-table.html, src/css/components/po-tabs/po-tabs.html, src/css/components/po-toolbar/po-toolbar.html, src/css/components/po-tree-view/po-tree-view.html, src/css/components/po-upload/po-upload.html, src/css/components/po-widget/po-widget.html, src/css/sample-app/po-menu.html, src/css/services/po-notification/po-toaster/po-toaster.html
**Po Style**
- Atualização do pacote `autoprefixer`
- Atualização do pacote `prettier`:
- Também foi atualizado os arquivos conforme as regras da nova atualização.
- Desabilitação das regras [arrowParens](https://prettier.io/docs/en/options.html#arrow-function-parentheses) e [trailingComma](https://prettier.io/docs/en/options.html#trailing-commas)
Para testar:
- Limpar a pasta node_module e executar comando `npm i`
- executar `npm run format:all` e verificar se não falta nenhuma regra nova. 
- executar o portal do `po-style` para ver se continua executando normalmente.
=> feat(packages): atualização dos pacotes

src/css/components/po-field/po-field-container/po-field-container.css
A definição de `position relative` para a classe `po-field-container` gerava efeito colateral de overflow no IE quando utilizado um input de seleção dentro do `po-container`.
**Simulação**
A classe `po-field-container` é amplamente utilizada pelos componentes `po-field`, então é recomendada a revisão dos componentes abaixo no portal.
- checkbox-group
- combo
- datepicker
- datepicker-range
- decimal
- input
- login
- lookup
- multiselect
- number
- password
- radio-group
- rich-text
- select
- switch
- textarea
- upload
Além do mencionado acima, atentar ao escopo da tarefa que é o teste em IE para um elemento `po-container` contendo um `po-select`. 
Fixes DTHFUI-3098
=> fix(field-container): corrige visualização no IE

src/css/components/po-table/po-table.html
Foi adicionado um exemplo de tabela utilizando a diretiva
'p-table-row-template' para customizar o posicionamento da arrow do
master-detail, colocando a mesma na posição da direita.
FIX DTHFUI-3718
PR com a implementação: https://github.com/po-ui/po-angular/pull/478
=> feat(table): adiciona exemplo de tabela com detail customizado

src/css/components/po-table/po-table.css, src/css/components/po-table/po-table.html
Alterado a posição padrão do íconde de ordenação de coluna do PO-TABLE,
passando da direita para a esquerda junto ao texto.
FIX DTHFUI-3798
=> feat(table): implementa nova posição do icone sort

src/css/components/po-field/po-combo/po-combo.html, src/css/components/po-field/po-input/po-input.css
Adiciona a propriedade p-clean no po-combo, permitindo limpar
o combo ao clicar no X localizado ao lado da seta de opções.
Fixes DTHFUI-2314, #152
=> feat(combo): adiciona a propriedade p-clean

src/css/components/po-table/po-table.css
Foi alterado uma atributo ao qual estava causando o bug que deixava o loading ocupado em todo espaço no chrome .
Fixes #667, MD8-38
=> fix(table): O loading esta ocupando todo o espaço no chrome

src/css/components/po-chart/po-chart.css
Necessário `overflow:visible` para correta exibição dos elementos svgs desenhados nas extremidades do viewBox
Fixes DTHFUI-2805
=> feat(chart): define overflow:visible para svg

src/css/components/po-field/po-select/po-select.css
A altura do campo estava 46px em +1366px e 34px em -1366px
fazendo que fique diferente dos demais.
A altura correta é 44px e 32px
Fixes DTHFUI-4636
=> fix(select): padroniza a altura do campo

src/css/components/po-chart/po-chart.css
Corrigida a situação de quando o gráfico interagia com outro elemento
como o menu, o resize não erá feito, causando distorção do gráfico
Fixes DTHFUI-4580
=> feat(chart): corrige resize do gráfico com elementos externos

src/css/components/po-chart/po-chart.css
Para os gráficos do tipo linha houve uma alteração de posicionamento em relação às categorias. Feito isso, foi necessário manter apenas as propriedades que centralizam o texto em relação à linha do eixo.
Fixes DTHFUI-2805
=> feat(chart): centraliza labels do eixo y

src/css/components/po-button/po-button.css
Adiciona Compatibilidade com outras fontes de ícones no componente po-button.
Fixes DTHFUI-1795
Obs: Ver [PR no po-angular](https://github.com/po-ui/po-angular/pull/830).
=> feat(button): adicionar compatibilidade com outras fontes de ícones

src/css/components/po-popup/po-popup.css
A pripriodade icon, permite informar outras fontes de ícones, até mesmo utilizando componentes via TemplateRef, mantendo a funcionalidade anterior.
Fixes DTHFUI-4906
=> feat(popup): adiciona possibilidade de informar outras fontes de ícones

src/css/components/po-table/po-table.css
**PO-TABLE**
**DTHFUI-4948**
O ícone de ações do componente `po-table` estava pequeno.
O ícone de ações do componente `po-table` teve um ajuste no tamanho.
Estava com 16px e foi alterado para 24px.
**Obs**
O ícone de mais detalhes também teve o tamanho alterado para 24px;
Em telas com resolução menor ou igual a 1366px ele tinha o tamanho de 16px e em telas com resolução maior que 1366px ele tinha o tamanho de 24px.
Também foi realizado ajuste nas bordas, corrigindo locais que precisavam ou não exibi-las.
**Simulação**
Bash -> `npm run build:portal && ng serve portal`
Powershell - > `npm run build:portal; ng serve portal`
=> feat(table): aumenta o tamanho do ícone de ações

src/css/components/po-button/po-button.css, src/css/components/po-disclaimer/po-disclaimer.css, src/css/components/po-field/po-checkbox/po-checkbox.css, src/css/components/po-field/po-switch/po-switch.css, src/css/components/po-table/po-table.css, src/css/components/po-tag/po-tag.css
corrige cursor pointer e warnings
- testar o cursor pointer que estava pegando em toda a aplicação
- buildar e validar que não vai mais aparecer os warnings ao subir a aplicação
- testar cursor do po-checkbox, habilitado e desabilitado
=> fix(style): corrige cursor pointer e warnings

src/css/components/po-button-group/po-button-group.html, src/css/components/po-field/po-rich-text/po-rich-text.html
Atualiza estilo dos componentes rich-text e button-group no app do CDN
Fixes DTHFUI-6023
Como testar
rodar o 'npm run watch' no po-style e depois em outro terminal na mesma pasta rodar o live-server
=> docs(button-group): atualiza estilo do componente

src/css/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.css
**RICH-TEXT**
Corrige o alinhamento dos botões no navegador Firefox.
Fixes DTHFUI-5598
=> fix(rich-text): corrige o alinhamento dos botões

src/css/components/po-widget/po-widget.css, src/css/themes/po-theme-default.css
Corrige comportamento que está apagando a borda de um widget não clicável com a propriedade `p-no-shadow`
fixes-DTHFUI-7003
=> fix(widget): corrige borda sendo apagada com p-no-shadow

src/css/components/po-list-view/po-list-view.css
Remove variável de cor não utilizada
- `--color-list-view-background-color`.
- `--color-list-view-border`.
Fixes DTHFUI-6999
BREAKING CHANGE: remove variáveis de customização de cores
- `--color-list-view-background-color`.
- `--color-list-view-border`.
Utilizar:
- `--border-color`.
- `--background`.
=> refactor(list-view): remove variável não utilizada

src/css/components/po-tooltip/po-tooltip.css
Corrige quebra de linha na tooltip com texto grande
fixes DTHFUI-7109
testar app:
```
<po-page-dynamic-table
p-title="Teste"
p-service-api="https://po-sample-api.fly.dev/v1/people"
[p-fields]="[{ property: 'id' }, { property: 'name' }]"
p-quick-search-width="6"
p-quick-search-value="35220553113791000637570000073806291214427288"
>
</po-page-dynamic-table>
<po-button p-label="Open Tooltip" p-tooltip="35220553113791000637570000073806291214427288"> </po-button>
```
=> fix(tooltip): corrige quebra de linha

src/css/components/po-tag/po-tag.css
Implementa área de click mínima de `44px` somente para a tag com `p-click` habilitada.
Fixes DTHFUI-7938
=> feat(tag): ajusta area de click minima

src/css/components/po-table/po-table.css
Comportamento atual:
Ao acessar o details do po-table e a largura do mesmo ultrapassa o tamanho da tela ocorre a quebra do po-table por inteiro e não só do details, assim criando um scroll horizontal para toda a tabela e desrespeitando os valores de largura das colunas da tabela principal, assim quebrando o layout proposto para a tela.
Comportamento esperado:
Como nas versões anteriores do PO-UI, como por exemplo a versão 15.9.0(versão anterior utilizado no projeto), onde quando a largura do detail ultrapassava a largura da tela, era criado um scroll horizontal dentro do próprio detail, respeitando os valores estipulados nas colunas tanto no detail quanto na tabela principal.
FIX DTHFUI-8133
=> fix(table): ajusta largura do template details

src/css/components/po-table/po-table.css
Adicionada propriedade `textWrap` para quebrar o texto excedente em várias linhas em pontos lógicos do texto.
fixes DTHFUI-8743
=> feat(grid): adiciona propriedade `textWrap`

src/css/commons/po-icon/po-icon-base.css, src/css/components/po-avatar/po-avatar.css, src/css/components/po-breadcrumb/po-breadcrumb.css, src/css/components/po-button/po-button.css, src/css/components/po-calendar/po-calendar.css, src/css/components/po-field/po-combo/po-combo.css, src/css/components/po-field/po-datepicker-range/po-datepicker-range.css, src/css/components/po-field/po-datepicker/po-datepicker.css, src/css/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.css, src/css/components/po-field/po-field-icon/po-field-icon.css, src/css/components/po-field/po-input/po-input.css, src/css/components/po-menu/po-menu-filter/po-menu-filter.css, src/css/components/po-modal/po-modal.css, src/css/components/po-page/po-page-login/po-page-login.css, src/css/components/po-table/po-table.css, src/css/components/po-toolbar/po-toolbar.css, src/css/components/po-tree-view/po-tree-view-item-header.css
PO_ICON
DTHFUI-8700
PR Checklist [Revisor]
[Padrão de Commit](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md) (Coeso, de acordo com o que está sendo realizado)
[Código](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md) (Boas práticas, nome de variavéis/métodos, etc.)
Testes unitários (Cobre a situação implementada e coverage está mantido)
[Documentação](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#documenta%C3%A7%C3%A3o) (Clara, objetiva e com exemplos caso necessário)
[Samples](https://github.com/po-ui/po-angular/blob/master/STYLEGUIDE.md#samples) (A implementação possui exemplo no Labs/Caso de uso)
Rodado em navegadores suportados (Chrome, FireFox, Edge)
Qual o comportamento atual?
Po-icon recebe o nome de um ícone através do parâmetro …
=> feat(icon): inclui dicionário de tokens

src/css/components/po-field/po-radio/po-radio.css
Ajusta centralização do `po-radio` ao reduzir o zoom da tela.
Fixes DTHFUI-8100
Simulação
[app.zip](https://github.com/po-ui/po-style/files/15163862/app.zip)
=> fix(radio): ajusta centralização do po-radio

docs/guides/icons.md, src/css/services/po-notification/po-toaster/po-toaster.css, src/css/themes/po-theme-default.css
Criar componente po-toaster e modo `inline` para mostrar componente diretamente no DOM. Componente também é utilizado pelo po-notification com o modo `alert`
fixes DTHFUI-8864
=> feat(toaster): criação do componente po-toaster

src/css/services/po-notification/po-toaster/po-toaster.css
Foi corrigido o z-index do po-toaster para não ficar sobreposto a outros componentes e a cor do ícone do tipo `warning` para cor escura no tema dark
fixes DTHFUI-9230
=> fix(toaster): corrige z-index e cor ícone warning no tema dark

src/css/components/po-tabs/po-tabs.css
Foi realizado uma correção no posicionamento do dropdown. (Ao utilizar o po-tabs com tabs agrupadas pelo dropdown o listbox não abre na posição correta estando dentro de um po-page-default)
fixes DTHFUI-9361
=> fix(tabs): corrige posicionamento do dropdown

src/css/components/po-info/po-info.css
O componente po-dynamic-view não preserva as quebras de linha dos dados recebidos da API. Adiciona a propriedade `p-text-wrap` para garantir que as quebras de linha (`\n`) sejam respeitadas na visualização dos dados.
Fixes DTHFUI-9446
=> feat(dynamic-view): adiciona propriedade p-text-wrap

src/css/components/po-toolbar/po-toolbar.css
Foi corrigido o posicionamento ao abrir a popup da notificação no toolbar, tanto em tamanhos de tela pequena, quanto grande.
fixes DTHFUI-9586 / issue 2172
=> fix(toolbar): corrige posicionamento do popup ao abrir notificação

src/css/components/po-table/po-table.css
**PO-Table**
**DTHFUI-9499**
Identificada incompatibilidade do virtual scroll com linhas de alturas indefinidas.
Possibilita desabilitar a propriedade p-virtual-scroll.
=> fix(table): possibilita desabilitar a propriedade p-virtual-scroll

src/css/components/po-table/po-table-column-link/po-table-column-link.css
corrige coluna do tipo link exibindo `ellipsis` caso dados não ficarem totalmente visíveis.
fixes DTHFUI-9883
=> fix(table): corrige coluna do tipo link

src/css/components/po-field/po-switch/po-switch.css
Corrige literals `rememberUser` que não estava aparecendo ao lado do switch
fixes DTHFUI-9751
=> fix(page-login): corrige literals rememberUser

src/css/components/po-field/po-multiselect/po-multiselect.css
DTHFUI-9649
Comportamento atual: 
Componente tinha a propriedade min-height: 2.75em o que define a altura baseado no elemento pai ao qual o elemento está vinculado;
Novo comportamento:
Alterado para a unidade "rem" (min-height: 2.75rem), que define a altura baseado no elemento raiz;
[app.zip](https://github.com/user-attachments/files/17574405/app.zip)
=> fix(multiselect): ajusta a referência de altura

src/css/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.css, src/css/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.css
Implementação da propriedade 'p-hide-toolbar-actions'. Com essa propriedade, será possível passar os botões do toolbar que serão ocultados do toolbar. Se for passado todas as opções existentes ('color', 'align', 'format', 'list', 'link', 'media'), a toolbar não será exibida.
fixes DTHFUI-9923
=> feat(richtext): inclusão propriedade para ocultar botões do toolbar

src/css/components/po-field/po-combo/po-combo.css, src/css/components/po-field/po-select/po-select.css, src/css/themes/po-theme-default.css
- Implementação das cores especificadas no handoff do Figma para os componentes po-combo e po-select.
Fixes #2154, chevron-down/DTHFUI-96
=> fix(chevron-down): ajusta cores dos componentes conforme AnimaliaDS

src/css/components/po-chart/po-chart.css
Implementação da propriedade 'p-data-label', onde é possível passar a propriedade `fixed`. Com essa propriedade (fixed=tue), irar alterar o grafico do tipo line.
- O valor da series ficar sendo exibido fixado com uma background transparente.
- Não será mostrado o tooltip ao hover do bullet.
- Será adicionado uma opacidade a todas outras series quando selecionado uma delas.
- O hover da serie ficará ate selecionar outra ou sair do gráfico.
fixes DTHFUI-10134
=> feat(chart): inclusão propriedade `p-data-label` para chart tipo `line`

src/css/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.css, src/css/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.html
Adiciona as propriedades:
- `p-error-limit` no `po-field-container-bottom`
- `p-field-error-limit` nos componentes `po-checkbox-group`, `po-combo`, `po-datepicker`, `po-datepicker-range`, `po-decimal`, `po-email`, `po-input`, `po-login`, `po-lookup`, `po-multiselect`, `po-number`, `po-password`, `po-radio group`, `po-rich-text`, `po-select`, `po-textarea`, `po-url`
- `errorLimit` na interface para o componente `po-dynamic-form-field` utilizado para os componentes `po-datepicker`, `po-input`, `po-number`, `po-decimal`, `po-password`, `po-datepicker-range`, `po-select`, `po-checkbox-group`, `po-radio-group`, `po-multiselect`, `po-combo`, `po-lookup`, `po-textarea`
- no componente `po-field-container-bottom`, a propriedade permite limitar a exibição da mensagem de erro a duas linhas e exibir …
=> feat(fields): adiciona limite na exibição de mensagens de erro

src/css/components/po-tabs/po-tab-button/po-tab-button.css, src/css/components/po-tabs/po-tabs.css, src/css/themes/po-theme-default.css
- Corrige aplicação da variável `--padding-tabs-header` no `po-page-default`
- Adiciona estilos personalizados para garantir padding correto nos tabs
Fixes DTHFUI-10847
=> feat(tabs): ajusta padding dos po-tabs dentro de po-page-default

src/css/components/po-tabs/po-tab-button/po-tab-button.css, src/css/themes/po-theme-default.css
O componente po-tabs implementa apenas o token --background, que altera a cor de fundo do componente por inteiro. Adiciona o token --background-item-default para permitir a customização da cor de fundo do item padrão separadamente da cor de fundo de todo o po-tabs.
Fixes: DTHFUI-10947
=> feat(tabs): adiciona o token --background-item-default

src/css/components/po-label/po-label.css
Implementa melhoria para resolver o problema onde os textos "(Obrigatório)" ou "(Opcional)" não quebravam linha em containers pequenos, causando overflow. A solução utilizada abrange componentes de formulário como:
- po-input
- po-dynamic-form
- demais componentes com po-label
Fixes DTHFUI-10940
=> feat(label): implementa quebra de linha para textos do requirement

src/css/components/po-field/po-lookup/po-lookup.css, src/css/components/po-page/po-page-list/po-page-list.css, src/css/components/po-table/po-table-column-manager/po-table-column-manager.css, src/css/components/po-table/po-table.css, src/css/components/po-tag/po-tag.css
A propriedade p-spacing do po-table disponibiliza atualmente três opções de espaçamento: large, medium e small.
Adiciona a opção de espaçamento extraSmall, que é disponibilizada automaticamente quando o nível de acessibilidade AA estiver configurado por meio do serviço de tema. Essa nova opção também passa a ser aplicada nos componentes que consomem o po-table, como po-lookup e po-dynamic-table.
fixes DTHFUI-10661
=> feat(table): adiciona tamanho extraSmall ao p-spacing

src/css/components/po-table/po-table.css
Corrige sobreposição de colunas fixas ao usar template cell, garantindo que elas fiquem acima do conteúdo customizado.
fixes DTHFUI-10907
=> fix(table): corrige sobreposição de colunas fixas com template cell
