po-ui/po-style

src/css/components/po-modal/po-modal.css
src/css/components/po-modal/po-modal.html

**PO-MODAL**
[DTHFUI-894](http://jiraproducao.totvs.com.br/browse/DTHFUI-894)
DTHFUI-1245 - Altera o valor "auto" para poder deixar a modal ter o tamanho conforme o conteúdo sem a limitação de tamanho.
**Situação:**
A modal estava limitando o tamanho do valor "auto" para `768px`.
**Solução:**
Alterado o valor "auto" para poder deixar a modal ter o tamanho conforme o conteúdo sem a limitação de tamanho.
**Simulação:** 
Utilizar o sample labs da modal
**OBS.:** Não foi possível testar no IE, pois o App.component do repositório não está com os polyfills corretos.

feat(modal): altera o valor "auto" para não limitar a largura

---

package.json

build: release v1.1.0

---

src/css/components/po-navbar/po-navbar-logo/po-navbar-logo.css
src/css/components/po-navbar/po-navbar.css

**PO NAVBAR**
**DTHFUI-1065**
Corrige a logo do navbar, o ícone do menu mobile que estava sobrepondo
a modal e também detalhes na responsividade
**Simulação**
Utilizar o portinari-angular para simular

fix(navbar): corrige detalhes na responsividade e logo

---

package.json

build: release v1.1.1

---

package.json

build: release 1.2.0

---

src/css/components/po-upload/index.css
src/css/components/po-upload/po-upload-drag-drop/index.css
src/css/components/po-upload/po-upload-drag-drop/po-upload-drag-drop-area-overlay/po-upload-drag-drop-area-overlay.css
src/css/components/po-upload/po-upload-drag-drop/po-upload-drag-drop-area/po-upload-drag-drop-area.css
src/css/components/po-upload/po-upload.html
src/css/themes/po-theme-default.css

**PO-UPLOAD**
**DTHFUI-653**
**Situação:**
O componente não tinha a opção de drag-drop
**Solução:**
Adicionadas classes de estilos para que o componente utilize ao aceitar drag and drop.
**Simulação:**
Verificar o sample
Importante validar também a [PR no TFS](https://totvstfs.visualstudio.com/THF/_git/portinari-theme/pullrequest/12439?_a=overview)

feat(upload): permite que o componente aceite drag and drop

---

package.json

build: release 1.3.0

---

package.json

build: release 1.3.1

---

src/app/components.json
src/css/components/index.css
src/css/components/po-progress/index.css
src/css/components/po-progress/po-progress-bar/po-progress-bar.css
src/css/components/po-progress/po-progress.css
src/css/components/po-progress/po-progress.html
src/css/themes/po-theme-default.css

**PO PROGRESS**
**DTHFUI-1435**
**Situação:**
Criar o componente po-progress-bar
**Solução:**
Implementa estilo do novo componente po-progress contendo
o po-progress-bar.
**Simulação:**
Utilizar a branch com o mesmo nome no portinari-angular. Também pode ser testado no portal.

feat(progress): cria o componente po-progress

---

package.json

build: release v1.4.0

---

src/css/components/po-tabs/po-tab-button/po-tab-button.css
src/css/components/po-tabs/po-tabs.css
src/css/components/po-tabs/po-tabs.html

**PO-TABS**
**Fixes DTHFUI-1416**
***
O componente são exibe corretamente as *labels* das *tabs* em telas pequenas.
Implementado tratamento para exibição das tabs em telas menores bem como acrescentado novo comportamento nos exemplos.
**Simulação**
Verificar exemplos.
**UI**
- https://github.com/portinariui/portinari-angular/pull/57

feat(tabs): possibilita scrollagem horizontal das tabs em telas pequenas

---

package.json

build: release v1.5.0

---

src/css/components/po-upload/index.css
src/css/components/po-upload/po-upload-file-restrictions/index.css
src/css/components/po-upload/po-upload-file-restrictions/po-upload-file-restrictions.css
src/css/components/po-upload/po-upload.html
src/css/themes/po-theme-default.css

**PO UPLOAD**
**DTHFUI-788**
**Situação:**
Exibir informações referente as restrições dos arquivos.
**Solução:**
Criado subcomponente para exibir as restrições via texto fixo (abaixo da area de drag drop e o botão de selecionar arquivo).
**Simulação:**
 Utilizar a branch com o mesmo nome no portinari-angular. Também pode ser testado no portal.

feat(upload): exibir restrições de arquivos

---

package.json

build: release v1.6.0

---

package.json

build: release v1.7.0

---

src/css/components/po-progress/po-progress.css
src/css/components/po-progress/po-progress.html

**PO PROGRESS**
**DTHFUI-1863**
**Situação:**
Criar o evento de tentar novamente
**Solução:**
Implementa um novo icone de "tentar novamente" que será exibido quando possuir o evento de retry e o status do componente for Error.
**Simulação:**
Realizar testes no portal utilizando a branch do portinari-angular.

feat(progress): adiciona evento de tentar novamente

---

src/css/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.css
src/css/components/po-field/po-rich-text/po-rich-text.html

Adicionada a função de alterar a cor do texto através de um novo botão na toolbar do componente, no qual executará as funções nativas de seleção de cores do navegador e aplicará ao texto selecionado e/ou as próximas digitações.
Fixes DTHFUI-1718
Feature: portinariui/portinari-angular#75

feat(rich-text): possibilita que usuário mude a cor do texto

---

src/css/components/po-upload/po-upload.css
src/css/components/po-upload/po-upload.html

Atualiza a barra de progresso para utilizar o componente po-progress,
utilizando o conceito de componentização .
Fixes DTHFUI-1587

feat(upload): passa a utilizar o po-progress como barra de progresso

---

src/css/components/po-upload/po-upload-drag-drop/po-upload-drag-drop-area/po-upload-drag-drop-area.css
src/css/components/po-upload/po-upload.html

Modifica o link do drag drop para utilizar a tag button.
Fixes DTHFUI-1720
**OBS.: ver PR do [portinari-theme](https://totvstfs.visualstudio.com/THF/_git/portinari-theme/pullrequest/14042?_a=overview)!**

feat(upload): modifica o link do drag drop

---

package.json

build: release v1.8.0

---

src/css/components/po-field/po-checkbox-group/po-checkbox-group.css
src/css/components/po-field/po-checkbox-group/po-checkbox-group.html

**PO-CHECKBOX-GROUP**
**DTHFUI-1611**
O texto fica sobreposto quando há quebra de linha em textos muito grandes.
Corrigido problema de espaçamento e alinhamento.
**Simulação**
Buildar e testar no portal e também visualizar os samples do CDN.
Obs:
Possui PR no portinari-angular e também no portinari-theme.

fix(checkbox-group): ajusta texto sobreposto.

---

package.json

build: release v1.8.1

---

gulpfile.js
package.json
src/app/index.html
src/css/commons/po-reset.css
src/css/index-modern.css
src/css/themes/po-theme-default.css

**BUILD**
**DTHFUI-1761**
Qual o comportamento atual?
O pacote publica apenas o arquivo final minificado do CSS.
Qual o novo comportamento?
O pacote passa a publicar o arquivo de variáveis para customização do
tema e um arquivo separado sem a "compilação" das variáveis, dando mais
flexibilidade para o desenvolvedor.
* Os pacotes de dependências também foram atualizados.

feat(build): adiciona novos arquivos ao pacote publicado

---

package.json

build: release v1.9.0

---

package.json

build: v1.10.0

---

src/app/components.json
src/css/components/index.css
src/css/components/po-accordion/index.css
src/css/components/po-accordion/po-accordion-item-body.css
src/css/components/po-accordion/po-accordion-item-header.css
src/css/components/po-accordion/po-accordion.css
src/css/components/po-accordion/po-accordion.html
src/css/themes/po-theme-default.css

Inserido estilização e exemplos do novo componente de acordo com o style guide.
As definições atuais possibilitam:
- Comportamento RESPONSIVO em mobile;
- A tecla [ TAB ] será utilizada para navegação por foco nos itens do accordion, somente nos itens de interação (cabeçalhos dos blocos de "mostra esconde");
- Efeito de _hover_ ao passar o mouse sobre o elemento.
As definições atuais não atendem:
- MENSAGEM DE FEEDBACK;
- ACESSIBILIDADE;
- ANIMAÇÕES.
https://app.zeplin.io/project/57bf4724a09dd68b60e7316f/screen/5cb779b450961164eeb9f76c (posição e ícones que devem ser usados)
Fixes DTHFUI-798

feat(accordion): adiciona o componente Accordion ao projeto

---

src/css/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.css
src/css/components/po-field/po-rich-text/po-rich-text.html

**RICH-TEXT**
**DTHFUI-1717**
Como usuário eu gostaria de poder incluir uma imagem através de drag drop ou incluindo uma URL. E também poder usar as opções de alinhamento também com as imagens.
Criado botão de inserir imagem que abre uma modal possibilitando ao usuário arrastar, selecionar ou incluir uma URL para inserir uma imagem no corpo do texto;

feat(rich-text): permite inclusão de imagem

---

package.json

build: release v1.11.0

---

src/css/commons/po-color-palette/po-color-palette.css
src/css/components/po-tag/po-tag.css
src/css/components/po-tag/po-tag.html
src/css/themes/po-theme-default.css

Propriedade p-inverse permite inverter as cores do componente.
Possibilita representação de status ativo e inativo.
Fixes DTHFUI-1763

feat(tag): permitir inversão das cores

---

src/css/components/po-field/po-rich-text/po-rich-text-body/po-rich-text-body.css
src/css/components/po-field/po-rich-text/po-rich-text.html
src/css/themes/po-theme-default.css

Definição de estilos default para links e atualização dos samples.
Fixes DTHFUI-1745

feat(rich-text): permite a inclusão de links

---

package.json

build: release v1.12.0

---

package.json

build: release v1.13.0

---

package.json

build: release v1.13.1

---

src/css/components/po-field/po-checkbox-group/po-checkbox-group.css
src/css/components/po-table/index.css
src/css/components/po-table/po-table-column-manager/po-table-column-manager.css
src/css/components/po-table/po-table.css
src/css/components/po-table/po-table.html
src/css/themes/po-theme-default.css

Adiciona uma nova funcionalidade, que permite gerenciar as colunas
que serão exibidas no componente e
também permite informar quantidade
maxima de colunas visiveis.
Fixes DTHFUI-1502

feat(table): adiciona gerenciador de colunas

---

package.json

build: release v1.14.0

---

src/css/components/po-field/po-combo/po-combo.html

Samples contemplando `po-combo-option-template`
Fixes DTHFUI-1893

feat(combo): permite customizar lista de itens exibidos

---

package.json

build: release v1.15.0

---

src/css/components/po-chart/index.css
src/css/components/po-chart/po-chart-types.css
src/css/components/po-chart/po-chart.css
src/css/components/po-tooltip/po-tooltip.css
src/css/themes/po-theme-default.css

Estilos referentes ao gráfico do tipo gauge.
Fixes DTHFUI-1738

feat(chart): adiciona estilos para gráficos gauge

---

src/app/components.json
src/css/components/index.css
src/css/components/po-tree-view/index.css
src/css/components/po-tree-view/po-tree-view-item-header.css
src/css/components/po-tree-view/po-tree-view-item.css
src/css/components/po-tree-view/po-tree-view.css
src/css/components/po-tree-view/po-tree-view.html
src/css/themes/po-theme-default.css

Adiciona novo componente tree-view
Fixes DTHFUI-1740

feat(tree-view): novo componente 

---

package.json

build: release v1.16.0

---

package.json

build: release v1.17.0

---

src/app/components.json
src/css/components/po-field/index.css
src/css/components/po-field/po-checkbox/po-checkbox.css
src/css/components/po-field/po-checkbox/po-checkbox.html
src/css/themes/po-theme-default.css

**PO-CHECKBOX**
**Fixes DTHFUI-2397**
***
*** 
N/A
Novo componente *checkbox*.
**Simulação**
Verificar os *samples*.
***
UI: https://github.com/portinariui/portinari-angular/pull/177

feat(checkbox): novo componente

---

src/app/components.json
src/app/index.html
src/css/components/index.css
src/css/components/po-grid/index.css
src/css/components/po-grid/po-grid-cell-action.css
src/css/components/po-grid/po-grid-cell-content.css
src/css/components/po-grid/po-grid-head.css
src/css/components/po-grid/po-grid.css
src/css/components/po-grid/po-grid.html

**BUILD**
**DTHFUI-2327**
Ocorre erro ao executar os build's do angular e style
Importado definições de estilo do componente po-grid de acordo comas alterações do UI e ajustado o arquivo do index de acordo com nova nomenclatura da distribuição.
**Simulação**
Buildar o repositório, iniciar `npm run watch`, subir em servidor local, realizar alteração em um arquivo e então salvar. Não deverá ocorrer erros na compilação.
UI: https://github.com/portinariui/portinari-angular/pull/157

fix(grid): adiciona arquivos css

---

src/css/components/po-tree-view/po-tree-view-item-header.css
src/css/components/po-tree-view/po-tree-view.html

Adiciona estilos referente a seleção de itens.
Fixes DTHFUI-2369

feat(tree-view): adiciona opção de seleção de item

---

src/css/components/po-info/po-info.css
src/css/components/po-info/po-info.html
src/css/themes/po-theme-default.css

Adiciona o estilo para o valor quando o mesmo for um link.
Fixes DTHFUI-2458

feat(info): possibilita transformar o valor em um link

---

package.json

build: release v1.19.0

---

src/css/components/po-field/po-combo/po-combo.css
src/css/components/po-field/po-combo/po-combo.html
src/css/themes/po-theme-default.css

Definidos estilos para título de grupos e criado sample HTML
Fixes DTHFUI-2192

feat(combo): permite agrupamento de itens

---

package.json

build: release v1.20.0

---

package.json

build: release v1.22.0

---

package.json

build: release v1.22.1

---

package.json

build: release v1.22.2

---

package.json

build: release v1.23.0

---

package.json

build: release v1.24.0

---

src/css/commons/po-common.css
src/css/components/po-navbar/po-navbar.css

**Dynamic View**
**DTHFUI-2798, [#258](https://github.com/portinariui/portinari-angular/issues/258)**
Ao tentar gerar o PDF de uma página que tenha mais de 1 uma página, não é gerado o arquivo corretamente, "imprimindo" apenas a 1ª página. O problema ocorre no Firefox, IE e Edge. O problema ocorre tanto usando o componente isolado ou dentro de um page.
Correção para poder imprimir todas as páginas nos navegadores Firefox, IE e Edge
**Simulação**
Utilizar o fonte do: https://stackblitz.com/edit/portinariui-sbvdnl?file=package.json
Observação: utilizar [PR do Angular](https://github.com/portinariui/portinari-angular/pull/280) para …

fix(dynamic-view): corrige impressão da página

---

CODE_OF_CONDUCT.md

Inclusão do código de conduta.

docs(code-of-conduct): inclusão de código de conduta

---

package.json

build: release v1.26.0

---

CHANGELOG.md
commitlint.config.js
package.json

Cria changelog.md e lint de commits.
Adiciona as dependências ao projeto:
- husky
- @commitlint/cli
- @commitlint/config-angular
- standard-version

docs(changelog): adiciona CHANGELOG.md

---

src/css/components/po-button/po-button.css

**Descrição da melhoria**
Melhoria no affordance dos botões adicionando o cursor pointer como padrão no componente e removendo quando o botão está desabilitado.
**Caso de uso**
Fora o botão primary que tem uma interação com o mouse hover, os demais botões não tem nenhuma ou são quase imperceptíveis, o que combinado ao fato de seu estilo não ser 3D, dificulta para o usuário identificar que o elemento é um botão e quando pode ou não ser interagido pelo mouse.
**Informações adicionais**
[Link da Issue no Portinari-Angular](https://github.com/portinariui/portinari-angular/issues/201)
[Mais detalhes sobre o affordance mouse cursos](https://usabilitypost.com/2009/10/26/mouse-cursor-affordance/)
**Demo**

feat(button): melhora no affordance dos botões com o uso do cursor

---

CHANGELOG.md
package.json

build: release v1.27.1

---

CHANGELOG.md
package.json

build: release v1.28.0
fixes DTHFUI-3093

build: release v1.28.0

---

CHANGELOG.md
package.json

build: release 2.0.0-beta.2

---

src/css/components/po-field/po-radio-group/po-radio-group.css
src/css/components/po-field/po-radio-group/po-radio-group.html

**radio-group**
**DTHFUI-3147**
Quando havia grande quantidade de caracteres em uma opção gerava sobreposição do texto sobre o input.
Acertos de margem e position para adequar à qualquer quantidade de caracteres. 
**Simulação**
Definido sample para textos grandes para visualização.
Testar também no portal.

fix(radio-group): corrige sobreposição de texto

---

CHANGELOG.md
package.json

build: release 2.0.0-beta.3

---

CHANGELOG.md
package.json

build: release 2.0.0-rc.1

---

src/css/components/po-field/po-lookup/po-lookup.html
src/css/components/po-table/po-table.css
src/css/components/po-table/po-table.html
src/css/themes/po-theme-default.css

Definidas classes css únicas para o radio-button usado no componente para tratamento de alinhamento e estilo.

fix(table): define css para radio-button

---

src/css/components/po-page/po-page-blocked-user/po-page-blocked-user.css

O ellipsis não estava funcionando adequadamente para as linhas de contatos.
Fixes DTHFUI-3195

fix(page-blocked-user): corrige ellipsis nos campos de contatos

---

CHANGELOG.md
package.json

build: release v2.1.0

---

CHANGELOG.md
package.json

build: release v2.2.0

---

CHANGELOG.md
package.json

build: release v2.3.0

---

CHANGELOG.md
package.json

build: release v2.4.0

---

CHANGELOG.md
package.json

build: release v2.4.1

---

src/css/components/po-page/po-page-list/po-page-list.css

folha de estilos complementar ao PR https://github.com/po-ui/po-angular/pull/432

feat(page-list): adiciona tamanho no filtro

---

CHANGELOG.md
package.json

build: release v2.6.0

---

CHANGELOG.md
package.json

build: release v2.7.0

---

src/css/components/po-avatar/po-avatar.html

Altera o sample do avatar, adicionando um exemplo clicável.
Fixes DTHFUI-1873

feat(avatar): adiciona exemplo clicável

---

src/css/components/po-table/po-table.css
src/css/components/po-table/po-table.html

Adiciona classe po-table-header-actions para omitir o gerenciador
de colunas do po-table.
FIXES DTHFUI-3580

feat(table): adiciona classe para utilizar ações sem o column manager

---

CHANGELOG.md
package.json

build: release v2.8.0

---

src/css/components/po-table/po-table.html

feat(table): adiciona sample de botão com loading na tabela

---

src/css/components/po-page/po-page-background/po-page-background.css
src/css/components/po-page/po-page-login/po-page-login.css
src/css/components/po-page/po-page-login/po-page-login.html
src/css/themes/po-theme-default.css

**Page Login**
**DTHFUI-3709**
Atualmente o template concatenava a palavra "Bem-vindo" junto com o nome do produto.
- modificação do sample e do css para o novo layout separando o "Bem-vindo" do nome do produto.
- alteração em algumas tags semânticas visando uma melhor acessibilidade para leitores de tela. 
**Simulação**
- usar o sample
**Validar:**
[PR Angular](https://github.com/po-ui/po-angular/pull/505) e [Tema customizado](https://github.com/totvs/po-theme-totvs/pull/46)
Fixes DTHFUI-3709

feat(page-login): modifica apresentação do cabeçalho

---

CHANGELOG.md
package.json

build: release v3.0.0-beta.1

---

src/css/components/po-page/po-page-login/po-page-login.css
src/css/components/po-page/po-page-login/po-page-login.html
src/css/themes/po-theme-default.css

**PO-PAGE-LOGIN**
**DTHFUI-3712**
Adiciona botão opcional de suporte ao template.
OBS: Possui PR também no [po-theme-totvs](https://github.com/totvs/po-theme-totvs/pull/49).

feat(page-login): adiciona botão de suporte

---

src/css/components/po-table/po-table.html

Adiciona exemplo de tabela utilizando o loading somente no
botão "Carregar mais resultados".
FIX DTHFUI-3911

feat(table): adiciona exemplo show more com loading

---

src/css/components/po-list-view/po-list-view.css
src/css/components/po-list-view/po-list-view.html

**PO-LIST-VIEW**
**DTHFUI-3908**
Incluída nova classe css para corrigir alinhamento da caixa de seleção.

fix(list-view): corrige alinhamento da caixa de seleção

---

CHANGELOG.md
package.json

build: release v3.3.0

---

src/css/components/po-navbar/po-navbar.css

**PO NAVBAR**
**DTHFUI-2633**
----------
**Comportamento atual:**
Ao incluir o navbar é gerado um scrollbar vertical desnecessário.
**Novo comportamento:**
Corrige scrollbar vertical gerado desnecessariamente.
**Importante**: Possui PR no po-angular. Foi necessário remover tratamento existente no portal.
**Simulação:**
Buildar a branch e colar na node_modules do po-angular. Possui html para ajudar na simulação na [PR do po-angular](https://github.com/po-ui/po-angular/pull/587).

fix(navbar): corrige scrollbar vertical desnecessário

---

.github/workflows/publish_style_ci.yml
.github/workflows/publish_theme_cli_ci.yml
package.json
src/cli/package.json

**@po-ui/style e @po-ui/theme-cli**
DTHFUI-1780
- Adicionar no github actions uma ação para publicar os pacotes style e theme-cli de forma automatizada.
- Remove a tag dev do package.json, para a partir dali os pacotes serem publicados utilizando a tag next e latest.
style: será acionado a ação quando for feito git tag <versão> e git push origin <versão>.
theme-cli: será acionado através de um botão na aba Actions, veja mais em [Executar um fluxo de trabalho manualmente](https://docs.github.com/pt/actions/configuring-and-managing-workflows/configuring-a-workflow#manually-running-a-workflow)
**Para testar:**
- Para chegar em um teste mais próximo, pode ser utilizado o repositório: https://github.com/nicoleoliveira/po-style-test-github-actions. Utilize esse repositório para subir as versões …

build(actions): cria ação de publicação do pacote

---

CHANGELOG.md
package.json

build: release v3.5.0

---

.github/workflows/publish_style_ci.yml
.github/workflows/publish_theme_cli_ci.yml

Altera o gatilho da publicação para ser acionado quando for clicado no botão.
Fixes DTHFUI-1780

build: altera gatilho para publicação

---

src/app/components.json
src/css/commons/po-common.css
src/css/components/po-page/index.css
src/css/components/po-page/po-page-slide/po-page-slide.css
src/css/components/po-page/po-page-slide/po-page-slide.html
src/css/components/po-page/po-page-slide/po-page-slide.js
src/css/themes/po-theme-default.css

**PO PAGE SLIDE**
**[#283](https://github.com/po-ui/po-angular/issues/283)**
Criação dos estilos do componente `po-page-slide`.

feat(page-slide): adiciona estilo para o componente po-page-slide

---

CHANGELOG.md
package.json

build: release v3.6.0

---

src/css/components/po-popup/po-popup.css
src/css/components/po-popup/po-popup.html
src/css/themes/po-theme-default.css

Adiciona altura maxima no elemento e faz que o scroll seja automatico.
PR PO Theme https://github.com/totvs/po-theme-totvs/pull/61
Fixes DTHFUI-3837

feat(popup): adiciona altura maxima no elemento

---

CHANGELOG.md
package.json

build: release v3.8.0

---

src/css/components/po-field/po-lookup/po-lookup.css
src/css/components/po-field/po-lookup/po-lookup.html
src/css/themes/po-theme-default.css

Adiciona funcionalidade de busca avançada para o po-lookup.
Fixes DTHFUI-487

feat(lookup): adiciona novo filtro de busca avançada

---

CHANGELOG.md
package.json

build: release v3.9.0

---

CHANGELOG.md
package.json

build: release v3.10.0

---

src/css/components/po-chart/po-chart.css
src/css/themes/po-theme-default.css

**PO-CHART**
**DTHFUI-1757**
Inclui PoChartType.Line.
**Simulação:**
Buildar e copiar a pasta style do interior da pasta dist e colar na pasta po-ui da node_modules no po-angular, buildar, subir o portal e abrir a aba de exemplos do po-chart.
**Obs: Possui branch no [po-angular](https://github.com/po-ui/po-angular/pull/660) e no [po-theme-totvs](https://github.com/totvs/po-theme-totvs/pulls).**

feat(chart): inclui PoChartType.Line

---

CHANGELOG.md
package.json

build: release v3.12.0

---

src/css/services/po-notification/po-toaster/po-toaster.css
src/css/services/po-notification/po-toaster/po-toaster.html

Melhorias no po-toaster, ajuste no espaçamento, resolução e centralização dos itens na tela.
Fixes TIS-2

feat(notification): atualiza espaçamentos

---

src/css/components/po-chart/po-chart.css

feat(chart): define animação para gráfico de linha

---

CHANGELOG.md
package.json

build: release v3.14.0

---

src/css/components/po-chart/po-chart.css

Definição de posicionamento dos textos do grid para gráficos do tipo barra.
Fixes DTHFUI-1755

feat(chart): estilo para gráficos do tipo Bar

---

CHANGELOG.md
package.json

build: release v4.0.0

---

src/cli/package.json

build: release theme-cli v4.0.0

build: release theme-cli v4.0.0

---

CHANGELOG.md
package.json

build: release v4.1.0

---

src/css/commons/po-color-palette/po-color-palette.css
src/css/components/index.css
src/css/components/po-gauge/index.css
src/css/components/po-gauge/po-gauge.css
src/css/themes/po-theme-default.css

po-gauge
DTHFUI-4341
Definição de estilos para o componente `po-gauge`

feat(gauge): adiciona componente gauge

---

CHANGELOG.md
package.json

build: release v4.2.0

---

src/css/components/po-chart/po-chart.css

Define estilo para label em gráficos do tipo Donut.
Fixes DTHFUI-4660

feat: estilo para label em gráficos do tipo Donut

---

CHANGELOG.md
package.json

build: release v4.4.0 

---

CHANGELOG.md
package.json

build: release v4.6.0

---

src/css/commons/po-color-palette/po-color-palette.css

Adicionadas classes para uso das cores-padrão para definição de borda.

feat(chart): classes para definição de cor de borda

---

CHANGELOG.md
package.json

build: release v4.7.0

---

CHANGELOG.md
package.json

build: release v4.8.0

---

src/css/commons/po-grid-system/index.css
src/css/commons/po-grid-system/po-grid-system-pull.css

Novas classes para funcionar em conjunto com a issue 585 no po-angular
Estas novas classes são necessárias para que a nova feature funcione

feat(po-dynamic): adiciona classes para espaçamento após o campo

---

CHANGELOG.md
package.json

build: release v4.9.0

---

src/css/commons/po-color/po-color.css

Inclusão das classes css para formatação de textos, como é feito no arquivo "po-color-palette.css"

feat(colors): Paleta de cores para textos

---

CHANGELOG.md
package.json

build: release v4.10.0

---

CHANGELOG.md
package.json

build: release v4.10.1

---

CHANGELOG.md
package.json

build: release v4.11.0

---

CHANGELOG.md
package.json

build: release v4.12.0

---

CHANGELOG.md
package.json

build: release v4.13.0

---

CHANGELOG.md
package.json

build: release v4.14.0

---

src/css/components/po-tag/po-tag.css

feat(tag): atualiza configurações para ícone no componente

---

CHANGELOG.md
package.json

build: release v4.16.1

---

src/css/components/po-field/po-field-icon/po-field-icon.css

Adiciona compatibilidade com outras fontes de ícones nos componentes PO-COMBO, PO-INPUT, PO-DECIMAL E PO-NUMBER.
Possui PR no [po-angular](https://github.com/po-ui/po-angular/pull/876).

feat(fields): adiciona compatibilidade com outras fontes de ícones.

---

src/css/components/po-calendar/po-calendar.css
src/css/components/po-calendar/po-calendar.html
src/css/themes/po-theme-default.css

feat(calendar): adiciona estilos para permitir modo range

---

CHANGELOG.md
package.json

build: release v5.0.0-rc.1

---

CHANGELOG.md
package.json
src/cli/package.json

build: release v5.0.0

---

CHANGELOG.md
package.json

build: release v5.1.0

---

src/css/components/po-field/po-datepicker-range/po-datepicker-range.css

feat(datepicker-range): adiciona estilo para calendario range

---

CHANGELOG.md
package.json

build: release 5.2.0

---

CHANGELOG.md
package.json

build: release v5.2.1

---

src/css/components/po-toolbar/po-toolbar.css

feat(toolbar): adiciona estilo para centralizar icones de outras fontes

---

CHANGELOG.md
package.json

build: release v5.3.0

---

CHANGELOG.md
package.json

build: release v5.4.0

---

src/css/components/po-field/po-multiselect/po-multiselect.css
src/css/components/po-field/po-multiselect/po-multiselect.html

feat(multiselect): adiciona estilos para a funcionalidade auto ajustavel

---

src/css/components/po-menu/po-menu.css

Inclui seletor para possibilitar outras fontes de ícones.

feat(menu): inclui seletor para possibilitar outras fontes de ícones

---

src/css/services/po-notification/po-toaster/po-toaster.css
src/css/services/po-notification/po-toaster/po-toaster.html

Adiciona estilo para o botão Fechar que foi implementado no componente,
fazendo com que torne desnecessario informar um botão fechar.
Fixes DTHFUI-5150

feat(notification): adiciona estilo para botão fechar

---

src/css/components/po-navbar/po-navbar-actions/po-navbar-action/po-navbar-action.css

Adiciona estilo para a centralização dos ícones no componente navbar.
Fixes DTHFUI-5137

feat(navbar): adiciona estilo para centralizar icones de outras fontes

---

CHANGELOG.md
package.json

build: release v5.7.0

---

CHANGELOG.md
package.json

build: release v5.8.0

---

src/css/services/po-notification/po-toaster/po-toaster.css

Realiza efeito de fade-in/out para o componente notification.
Fixes DTHFUI-5060

feat(notification): insere animação fade-in/out para o componente

---

src/css/components/po-field/po-multiselect/po-multiselect.css
src/css/components/po-field/po-multiselect/po-multiselect.html

Ajusta alinhamento do PoLoading para utilização no Multiselect com serviço.
Fixes DTHFUI-1104

feat(multiselect): ajusta exibição do loading interno

---

src/css/components/po-calendar/po-calendar.css
src/css/components/po-field/po-datepicker/po-datepicker.css

Renomeia classe e altera local de arquivo
Fixes DTHFUI-4615

refactor(datepicker): renomeia classe e altera local de arquivo

---

src/css/components/po-table/po-table.css

Inclui seletor para possibilitar outras fontes de ícones.

feat(table): adiciona compatibilidade com outras fontes de ícones

---

CHANGELOG.md
package.json

build: release v5.10.0

---

CHANGELOG.md
package.json

build: release v5.11.0

---

src/css/components/po-page/po-page-login/po-page-login.css

Classes para posicionar os campos de login e ícones de dica.
fixes : DTHFUI-5136

feat(page-login): adiciona classes para posicionamento dos fields

---

CHANGELOG.md
package.json

build: release v5.12.0

---

CHANGELOG.md
package.json

build: release v5.13.0

---

CHANGELOG.md
package.json

build: release v5.13.1

---

src/css/components/po-field/po-multiselect/po-multiselect.css

Adiciona estilo de campo indeterminate no item para selecionar todos.

feat(multiselect): adiciona estilo de campo indeterminate

---

CHANGELOG.md
package.json

build: release v5.14.0

---

CHANGELOG.md
package.json

build: release v5.15.0

---

src/css/components/po-calendar/po-calendar.css

**CALENDAR**
**DTHFUI-5464**
Adiciona estilo para o componente `calendar`.

feat(calendar): adiciona botão `hoje`

---

src/css/components/po-modal/po-modal.css

Adiciona estilo para o PoModalFooter
fixes DTHFUI-4864

feat(modal-footer): adiciona estilo para componente

---

CHANGELOG.md
package.json

build: release v5.20.0

---

CHANGELOG.md
package.json

build: release v5.21.0

---

CHANGELOG.md
package.json

build: release v5.22.0

---

CHANGELOG.md
package.json

build: release v5.22.1

---

CHANGELOG.md
package.json

build: release v6.0.0-rc.1

---

CHANGELOG.md
package.json

build: release v5.22.2

---

CHANGELOG.md
package.json

build: release v6.0.0

---

src/cli/package.json

build(theme-cli): release v6.0.0

build(theme-cli): release v6.0.0

---

CHANGELOG.md
package.json

build: release v6.1.0

---

CHANGELOG.md
package.json

build: release v.5.22.3

---

CHANGELOG.md
package.json

build: release v5.22.4

---

src/css/components/po-button/po-button.css
src/css/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.css
src/css/themes/po-theme-animaliads.css
src/css/themes/po-theme-default.css

Ani button - modifica estilo do componente
DTHFUI - 5434

Ani button - modifica estilo do componente

---

src/css/components/po-menu/po-menu.html

Adiciona tag `<nav>` deixando o menu mais acessível.
Fixes DTHFUI-5760

feat(menu): melhora acessibilidade ao menu

---

CHANGELOG.md
package.json

build: release v6.5.0

---

CHANGELOG.md
package.json

build: release v5.22.5

---

CHANGELOG.md
package.json

build: release v6.5.1

---

CHANGELOG.md
package.json

build: release v6.6.0

---

CHANGELOG.md
package.json

build: release v5.22.7

---

CHANGELOG.md
package.json

build: release v6.7.0

---

src/css/components/po-field/po-checkbox/po-checkbox.css
src/css/themes/po-theme-default.css

Melhora acessibilidade e contraste do componente checkbox.
adiciona nova variável para a customização do background quando o checkbox está desabilitado e ativo
- color-checkbox-background-color-active-disabled
adiciona nova variável para a customização da cor do hover do checkbox
- color-checkbox-hover-active
fixes - DTHFUI-5841

feat(checkbox): melhora acessibilidade e contraste do componente

---

CHANGELOG.md
package.json

build: release v6.8.0

---

src/css/components/po-table/po-table-column-manager/po-table-column-manager.css
src/css/components/po-table/po-table.css

Altera o comportamento de scroll vertical na tabela.
Caso o scroll vertical seja exibido ele ficará
fixo na lateral.
DTHFUI-5752

feat(table): fixa scroll vertical

---

CHANGELOG.md
package.json

build: release v6.9.0

---

src/css/components/po-button-group/po-button-group.css
src/css/components/po-button/po-button.css
src/css/components/po-button/po-button.html
src/css/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.css
src/css/components/po-field/po-rich-text/po-rich-text.html
src/css/themes/po-theme-default.css

Aplicação de novo estilo definido pelo design system com remoção, alteração e inclusão de variáveis.
Melhoria de acessibilidade através do contraste das cores e focus visível no componente.
Variáveis adicionadas:
-  --color-secondary-light-40;
- --color-danger-light-05;
- --color-danger-light-20;
- --color-outline-focused;
- --color-button-box-shadow;
- --color-button-border-color-link;
Variáveis removidas:
- --color-button-color-primary-hover
- --color-button-color-primary-pressed
- --color-button-border-primary-disabled

feat(button): aplica estilo definido pelo design system

---

CHANGELOG.md
package.json

build: release v6.10

---

CHANGELOG.md
package.json

build: release v6.10.1

---

CHANGELOG.md
package.json

build: release v6.11.0

---

src/css/components/po-table/po-table.html

**TABLE**
**DTHFUI-6066**
**Simulação**
Executar o comando `npm run watch` em uma aba do terminal e `npm run dev` em outra aba de terminal.

feat(table): adiciona po-checkbox na po-table

---

src/css/components/po-table/po-table.css

Ajusta estilo ao utilizar na table virtual scroll 
DTHFUI-5921

feat(table): implementa virtual scroll

---

CHANGELOG.md
package.json

build: release v6.12.0

---

src/css/components/po-button-group/po-button-group.css

**BUTTON-GROUP**
Ajusta o visual do botão para o conteúdo ser exibido apenas em uma linha
**Fixes: DTHFUI-6167**

fix(button-group): corrige quebra de linha

---

CHANGELOG.md
package.json

build: release v6.12.1

---

src/css/components/po-list-view/po-list-view.css
src/css/components/po-list-view/po-list-view.html

Substitui o checkbox existente no po-list-view pelo po-checkbox.
Fixes DTHFUI-6150

feat(list-view): adiciona po-checkbox no `po-list-view`

---

src/css/components/po-table/po-table-column-manager/po-table-column-manager.css

insere estilo das setas do gerenciador de colunas da tabela
fixes DTHFUI-6147

feat(table): insere estilo das setas do gerenciador

---

src/app/components.json
src/css/components/po-field/index.css
src/css/components/po-field/po-radio/po-radio.css
src/css/components/po-field/po-radio/po-radio.html
src/css/themes/po-theme-default.css

Cria componente interno de radio, seguindo as regras de estilo do AnimaliaDS
Fixes: DTHFUI-6067

feat(radio): cria novo componente po-radio

---

src/css/components/po-button/po-button.css
src/css/components/po-button/po-button.html
src/css/themes/po-theme-default.css

Permite a utilização do kind primary com a propriedade danger habilitada
Fixes DTHFUI-6002

feat(button): inclui estilo kind primary danger

---

src/css/components/po-button/po-button.css
src/css/components/po-button/po-button.html
src/css/components/po-dropdown/po-dropdown.css
src/css/components/po-field/po-checkbox-group/po-checkbox-group.css
src/css/components/po-field/po-combo/po-combo.css
src/css/components/po-field/po-datepicker-range/po-datepicker-range.css
src/css/components/po-field/po-field-icon/po-field-icon.css
src/css/components/po-field/po-input/po-input.css
src/css/components/po-field/po-lookup/po-lookup.css
src/css/components/po-field/po-multiselect/po-multiselect.css
src/css/components/po-field/po-radio-group/po-radio-group.css
src/css/components/po-field/po-select/po-select.css
src/css/components/po-field/po-switch/po-switch.css
src/css/components/po-field/po-textarea/po-textarea.css
src/css/components/po-info/po-info.css
src/css/components/po-page/po-page-list/po-page-list.css
src/css/components/po-page/po-page-login/po-page-login.css
src/css/components/po-upload/po-upload.css

Foi removida a função @media screen dos estilos dos componentes
Fixes DTHFUI-5852

refactor(components): remove redimensionamentos

---

src/css/services/po-notification/po-toaster/po-toaster.css

Implementa novas definições para pequenas resoluções.
Fixes DTFUI-6203

feat(toaster): implementa para pequenas resoluções

---

src/css/components/po-tree-view/po-tree-view-item-header.css

Ajustado estilo do PoCheckbox.

feat(tree-view): ajusta estilo do po-checkbox

---

CHANGELOG.md
package.json

build: release v14.0.0-next.0

---

CHANGELOG.md
package.json

build: release v14.0.0-rc.0

---

src/css/components/po-table/po-table-column-manager/po-table-column-manager.css
src/css/components/po-table/po-table.css

TABLE
Ajusta o visual da tabela.
Fixes: DTHFUI-6154

fix(table): corrige quebra de colunas

---

CHANGELOG.md
package.json
src/cli/package.json
src/css/themes/po-theme-default.css

build: release v14.0.0

---

CHANGELOG.md
package.json

build: release v14.1.0

---

CHANGELOG.md
package.json

build: release v14.2.0

---

CHANGELOG.md
package.json

build: release v14.2.1

---

src/css/components/po-button/po-button.css
src/css/components/po-button/po-button.html
src/css/components/po-field/po-rich-text/po-rich-text-toolbar/po-rich-text-toolbar.css
src/css/components/po-list-view/po-list-view.css
src/css/components/po-table/po-table-column-manager/po-table-column-manager.css
src/css/components/po-table/po-table.css
src/css/themes/po-theme-default.css

**BUTTON**
Adiciona estilo para o `po-button` com tamanho `large`.
Deprecia a propriedade `p-small` e ajusta o estilo dos componentes que utilizavam o botão com tamanho reduzido.
DTHFUI-6022, DTHFUI-6353

feat(button): adiciona a propriedade `p-size` e deprecia a propriedade `p-small`

---

CHANGELOG.md
package.json

build: release v14.3.0

---

CHANGELOG.md
package.json

build: release v14.3.1

---

src/css/components/po-field/po-switch/po-switch.css
src/css/components/po-page/po-page-login/po-page-login.css
src/css/themes/po-theme-default.css

Aplicação de novo estilo definido pelo design system.
Melhoria de acessibilidade através do contraste das cores e focus visível no componente.
Fixes DTHFUI-6352

feat(switch): aplica estilo definido pelo DS

---

src/css/components/po-button/po-button.css
src/css/components/po-table/po-table-column-manager/po-table-column-manager.css

Corrige posicionamento do checkbox e botão do gerenciador de colunas
fixes DTHFUI-6386

fix(table): corrige posicionamento do gerenciador

---

src/css/components/po-field/po-checkbox/po-checkbox.css
src/css/components/po-field/po-radio-group/po-radio-group.css
src/css/components/po-field/po-radio-group/po-radio-group.html
src/css/components/po-field/po-radio/po-radio.css
src/css/components/po-field/po-radio/po-radio.html
src/css/themes/po-theme-default.css

Aplicação de novo estilo definido pelo design system.
Melhoria de acessibilidade através do contraste das cores e focus visível no componente.
Fixes DTHFUI-5861

feat(radiogroup): aplica estilo e acessibilidade definidos pelo DS

---

src/css/components/po-field/po-input/po-input.css
src/css/components/po-field/po-select/po-select.css
src/css/components/po-field/po-select/po-select.html
src/css/themes/po-theme-default.css

Aplica novo estilo definido pelo design system.
Melhoria de acessibilidade através do contraste das cores e focus visível no componente.
Fixes DTHFUI-6443

feat(select): aplica estilo e acessibilidade definidos pelo DS

---

src/css/components/po-field/po-input/po-input.css
src/css/components/po-field/po-textarea/po-textarea.css
src/css/components/po-field/po-textarea/po-textarea.html
src/css/themes/po-theme-default.css

Aplica estilo definido pelo AnimaliaDS
Fixes DTHFUI-6442

feat(textarea): aplica estilo e acessibilidade definidos pelo DS

---

src/css/components/po-button-group/po-button-group.css
src/css/themes/po-theme-default.css

Aplica estilo definido pelo AnimaliaDS no button-group
Fixes DTHFUI-6451

feat(button-group): aplica estilo definido pelo AnimaliaDS

---

CHANGELOG.md
package.json

build: release v14.6.0

---

src/css/components/po-button/po-button.css

Remove outlline em botão nativo e em componentes que não são `po-button`
fixes DTHFUI-6567
Teste: labs do button no portal e app :
```
<po-button p-label="PO Button" > </po-button>
<po-button p-kind="primary" p-label="PO Button" > </po-button>
<po-button p-kind="tertiary" p-label="PO Button" > </po-button>
<hr>
<button class="po-button po-button-primary">Botao nativo primary</button>
<button class="po-button po-button-default">Botao nativo secondary</button>
<button class="po-button po-button-link">Botao nativo tertiary</button>
<hr>
<po-table [p-items]="[{ table: 'PO Table', angular: 'PO-UI' }]"> </po-table>
<hr>
<po-accordion>
<po-accordion-item p-label="PO Accordion 1">
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</po-accordion-item>
<po-accordion-item p-label="PO …
```

fix(button): remove outline em botão nativo

---

src/css/components/po-field/po-checkbox/po-checkbox.css
src/css/components/po-field/po-checkbox/po-checkbox.html

Permite utilizar o tamanho large de acordo com as definições do AnimaliaDS.
Fixes DTHFUI-6452

feat(checkbox): inclui p-size: large

---

src/app/components.json
src/css/components/index.css
src/css/components/po-link/index.css
src/css/components/po-link/po-link.css
src/css/components/po-link/po-link.html
src/css/themes/po-theme-default.css

Cria componente de link, seguindo as regras de estilo do AnimaliaDS.
Fixes: DTHFUI-6508

feat(link): cria novo componente po-link

---

CHANGELOG.md
package.json

build: release v14.7.0

---

CHANGELOG.md
package.json

build: release 14.7.1

---

src/css/components/po-field/po-radio/po-radio.css

Remove a propriedade outline no click do radio
fixes DTHFUI-6657

feat(radio-group): remove propriedade outline

---

src/css/components/po-widget/po-widget.css
src/css/themes/po-theme-default.css

feat(widget): implementa definições do AnimaliaDS

---

src/css/components/index.css
src/css/components/po-field/po-field-container/po-field-container.css
src/css/components/po-label/index.css
src/css/components/po-label/po-label.css
src/css/themes/po-theme-default.css

Cria componente de label, seguindo as regras de estilo do AnimaliaDS
Fixes DTHFUI-6574

feat(label): novo componente po-label

---

src/css/components/po-field/po-field-container/po-field-container.css
src/css/components/po-field/po-select/po-select.css

Select/dthfui 6588 DTHFUI-6667

Select/dthfui 6588 e DTHFUI-6667

---

CHANGELOG.md
package.json

build: release v14.8.1

---

src/css/components/index.css
src/css/components/po-image/index.css
src/css/components/po-image/po-image.css
src/css/components/po-image/po-image.html

feat(po-image): adiciona estilo ao componente

feat(po-image): adiciona estilo ao componente

---

src/css/components/po-field/po-input/po-input.css

Remove propriedade `outer-spin-button` responsável pelo botão giratório dos `input`
Fixes DTHFUI-6666

feat(number): implementa definições do AnimaliaDS

---

src/css/components/po-divider/po-divider.css
src/css/themes/po-theme-default.css

Aplica novo estilo definido pelo design system.
Fixes DTHFUI-6663

feat(divider): aplica estilo definido pelo DS

---

src/css/components/po-tag/po-tag.css
src/css/themes/po-theme-default.css

Aplica novo estilo definido pelo design system.
Aplica melhoria de acessibilidade e usabilidade através do contraste das cores e customização de texto.
Fixes DTHFUI-6664

feat(tag): aplica estilo definido pelo DS

---

CHANGELOG.md
package.json

build: release v14.9.0

---

CHANGELOG.md
package.json

build: release v14.9.1

---

src/css/components/po-field/po-datepicker/po-datepicker.css
src/css/components/po-field/po-field-container/po-field-container.css

Implementa definições de estilo e acessibilidade do AnimaliaDS.
Fixes DTHFUI-6734

feat(datepicker): implementa definições Animalia DS

---

CHANGELOG.md
package.json

build: release v14.10.0

---

src/css/components/po-field/po-switch/po-switch.css
src/css/themes/po-theme-default.css

refactor(switch): remove variavel `--color-switch-color-label`

refactor(switch): remove variavel `--color-switch-color-label`

---

src/css/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.css
src/css/components/po-field/po-field-container/po-field-container.css
src/css/themes/po-theme-default.css

feat(fields): implementa definições do AnimaliaDS

feat(fields): implementa definições do AnimaliaDS

---

src/css/components/po-button/po-button.css
src/css/components/po-tooltip/po-tooltip.css
src/css/themes/po-theme-default.css

feat(tooltip): implementa definições do AnimaliaDS

---

src/css/components/po-field/po-field-container/po-field-container.css

fix(fields): ajusta posicionamento do rich-text
https://user-images.githubusercontent.com/42390783/205657837-2acf666c-29ef-44ba-9126-3f6821e63db1.mp4

fix(fields): ajusta posicionamento do rich-text

---

CHANGELOG.md
package.json

build: release v14.12.1

---

CHANGELOG.md
package.json

build: release v14.2.2

---

src/css/components/po-button/po-button.css

refactor(button): remove a propriedade p-type

refactor(button): remove a propriedade p-type

---

CHANGELOG.md
package.json

build: release v15.0.0-next.0

---

CHANGELOG.md
package.json

build: release v15.0.0-next.1

---

src/css/themes/po-theme-default.css

Corrige o valor da variável --background-danger-pressed conforme definido no Handoff.
Testar no portal local.
PR Theme Totvs https://github.com/totvs/po-theme-totvs/pull/208

fix(button): corrige background-danger-pressed

---

CHANGELOG.md
package.json

build: release v15.0.0-rc.0

---

CHANGELOG.md
package.json

build: release v15.0.0

---

CHANGELOG.md
package.json

build: release v15.0.1

---

CHANGELOG.md
package.json

build: release v15.1.0

---

src/css/components/po-field/po-input/po-input.css

**COMBO**
**DTHFUI-7042**
**Simulação**
Portal e Utilizar esse [app.zip](https://github.com/po-ui/po-style/files/10675341/app.zip)

fix(combo): corrige texto sobrepondo o `clean`

---

CHANGELOG.md
package.json

build: release v15.1.1

---

src/css/components/index.css
src/css/components/po-listbox/index.css
src/css/components/po-listbox/po-item-list/po-item-list.css
src/css/components/po-listbox/po-item-list/po-item-list.html
src/css/components/po-listbox/po-listbox.css
src/css/components/po-listbox/po-listbox.html
src/css/components/po-popup/po-popup.css
src/css/themes/po-theme-default.css

Cria componente de acordo com as definições de estilo e acessibilidade definidos pelo design system.
Fixes DTHFUI-6733

feat(listbox): novo componente

---

src/css/components/po-page/po-page-background/po-page-background.css
src/css/components/po-page/po-page-blocked-user/po-page-blocked-user.html
src/css/components/po-page/po-page-change-password/po-page-change-password.html
src/css/components/po-page/po-page-login/po-page-login.html
src/css/sample-app/po-page-login.html

Altera classe do componente `po-page-background`:
| Before                                             | After                                                          |
| ------------------------------------- | ---------------------------------------------|
| .po-page-background-main-logo | .po-page-background-main-logo-image |
Fixes DTHFUI-6808

refactor(page-background): altera classe

---

CHANGELOG.md
package.json

build: release v15.2.0

---

CHANGELOG.md
package.json

build: release v15.4.0

---

src/css/commons/po-reset.css

Adiciona a tipografia para o body, code e títulos seguindo as definições do animalia.

feat(typography): adiciona tipografia

---

CHANGELOG.md
package.json

build: release v15.5.0

---

src/css/components/po-field/po-field-icon/po-field-icon.css
src/css/components/po-field/po-input/po-input.css
src/css/components/po-field/po-select/po-select.css
src/css/themes/po-theme-default.css

**INPUT** 
**DTHFUI-6995**
Theme Totvs
https://github.com/totvs/po-theme-totvs/pull/221

fix(input): ajusta estilização

---

CHANGELOG.md
package.json

build: release v15.5.1

---

src/css/components/po-field/po-checkbox-group/po-checkbox-group.css
src/css/components/po-field/po-checkbox/po-checkbox.css
src/css/components/po-field/po-radio-group/po-radio-group.css
src/css/themes/po-theme-default.css

feat(checkbox): implementa definições do AnimaliaDS

---

CHANGELOG.md
package.json

build: release v15.6.0

---

CHANGELOG.md
package.json

build: release v15.6.1

---

src/css/components/po-field/po-multiselect/po-multiselect.css

Permite utilizar template customizado na label do componente `po-multiselect`
fixes DTHFUI-4672

feat(multiselect): permite utilizar template

---

src/css/components/po-link/po-link.css
src/css/components/po-table/po-table-column-link/po-table-column-link.css

Ajusta estilo do link em `table-column-link`
fixes DTHFUI-7204

feat(table): ajusta estilo

---

CHANGELOG.md
package.json

build: release v15.7.0

---

src/css/components/po-field/po-radio/po-radio.css

**RADIO**
fix(radio): ajusta `outline do focus`
**Simulação**
[portal](https://po-ui.io/documentation/po-radio-group)

fix(radio): ajusta `outline do focus`

---

src/css/components/po-modal/po-modal.css

**MODAL**
Ajusta propriedade CSS `justify-content`
**Simulação**
Rodar portal e acompanhar build.

fix(modal): ajusta propriedade CSS

---

src/css/components/po-list-view/po-list-view.css

Utilizar o componente PoButton para exibir os detalhes nos itens do PoListView.
Fixes DTHFUI-7215
**Simulação**
Testar no portal

feat(list-view): utiliza o pobutton para exibir os detalhes

---

CHANGELOG.md
package.json

build: release v15.8.0

---

CHANGELOG.md
package.json

build: release v15.8.1

---

CHANGELOG.md
package.json

build: release v15.8.2

---

src/css/components/po-tag/po-tag.css
src/css/themes/po-theme-default.css

**tag**
**DTHFUI-6870**
**PR Checklist [Revisor]**
**Simulação**
[app.zip](https://github.com/po-ui/po-style/files/11531472/app.zip)

feat(tag): implementa novas propriedades

---

CHANGELOG.md
package.json

build: release v15.9.0

---

src/css/components/po-tag/po-tag.css

**TAG**
**DTHFUI-7401**
__________________________

fix(tag): ajusta interferência na definição de cor

---

src/css/components/po-page/po-page-login/po-page-login.css

Centraliza a tag h1 no page-login
fixes #1743, DTHFUI-7429

fix(page-login): centraliza tag h1

---

CHANGELOG.md
package.json

build: release v15.11.0

---

src/css/components/po-table/po-table.css

Corrige estilização de única ação quando desabilitada
fixes DTHFUI-7461
app do po-angular para realizar teste do funcionamento:
[app.zip](https://github.com/po-ui/po-style/files/12033348/app.zip)
pasta style do build para substituir na node-modules do po-angular:
[style.zip](https://github.com/po-ui/po-style/files/12039699/style.zip)

fix(table): corrige única ação desabilitada

---

CHANGELOG.md
package.json

Este PR marca a nova versão 15.12.1 do nosso projeto.

build: release v15.12.1

---

src/css/commons/po-common.css
src/css/components/po-menu/index.css
src/css/components/po-menu/po-menu-filter/po-menu-filter.css
src/css/components/po-menu/po-menu-item/po-menu-item.css
src/css/components/po-menu/po-menu.css
src/css/themes/po-theme-default.css

feat(menu): implementa definições do AnimaliaDS

---

src/css/components/po-field/po-multiselect/po-multiselect.css
src/css/components/po-listbox/po-item-list/po-item-list.css
src/css/components/po-listbox/po-listbox.css
src/css/themes/po-theme-default.css

definição animalia ds no multiselect

---

src/css/components/po-table/po-table.css

estiliza classe de ações em lote.
fixes #DTHFUI-7317

feat(table): estiliza ações em lote

---

src/css/components/po-table/po-table.css

estiliza classe de drag and drop para a tabela.
fixes #DTHFUI-7315

feat(table): implementa drag and drop na tabela

---

CHANGELOG.md
package.json

Este PR marca a nova versão v15.13.0 do nosso projeto.

build: release v15.13.0

---

CHANGELOG.md
package.json

build: release v15.13.1

---

src/css/components/po-button/po-button.css
src/css/components/po-table/po-table.css

Implementa possibilidade de fixar uma ou até 5 colunas da tabela
fixed DTHFUI-7314

feat(table): implementa fixador de colunas

---

CHANGELOG.md
package.json

build: release v15.14.0

---

src/css/components/index.css
src/css/components/po-search/index.css
src/css/components/po-search/po-search.css
src/css/components/po-table/po-table.css
src/css/themes/po-theme-default.css

**TABLE**
**DTHFUI-7318**
**ADICIONA ESTILO AO IMPLEMENTAR BUSCA NA TABELA**

feat(search): implementa busca na tabela

---

CHANGELOG.md
package.json

build: release v16.0.0-next.0

---

src/css/components/po-field/po-lookup/po-lookup.css

**LOOKUP**
**Ajusta inconsistência na propriedade `p-disabled`.**
**Simulação:** [app.zip](https://github.com/po-ui/po-style/files/12422102/app.zip)

fix(lookup): ajusta propriedade `p-disabled`

---

src/css/components/po-listbox/po-listbox.css

implementa o uso do listbox no componente.
Fixed DTHFUI-7319

feat(combo): implementa o listbox no componente

---

src/css/components/po-field/po-checkbox/po-checkbox.css
src/css/components/po-field/po-combo/po-combo.css

Valida campos obrigatórios com borda vermelha
fixes DTHFUI-7478

fix(page-edit): valida campos obrigatórios

---

src/css/components/po-table/po-table-column-link/po-table-column-link.css
src/css/components/po-table/po-table.css

alinhamento de colunas do tipo number, currency, subtitle
Fixes 7668

fix(table): alinhamento de colunas do tipo number, currency, subtitle

---

src/css/components/po-table/po-table.css
src/css/themes/po-theme-default.css

Corrige cor da linha selecionada ao utilizar tabela selecionável
fixes DTHFUI-7772

fix(table): corrige cor da linha selecionada

---

CHANGELOG.md
package.json

build: release 16.2.1

---

src/css/components/po-field/po-input/po-input.css

adiciona indicação visual de campo invalido no `po-input`
Fixes 7479

fix(input): adiciona indicação visual de campo inválido

---

CHANGELOG.md
package.json

build: release v16.3.0

---

src/css/components/po-menu/po-menu-item/po-menu-item.css
src/css/components/po-menu/po-menu.css

Ajusta a aparência do componente nos navegadores Safari e Firefox.
Fixes DTHFUI-7743

fix(menu): ajusta aparencia do menu

---

src/css/components/po-tag/po-tag.css
src/css/components/po-tag/po-tag.html

Implementa variação de status `neutral` de acordo com definições do AnimaliaDS

feat(tag): implementa variação de status `neutral`

---

src/css/components/po-accordion/po-accordion-item-header.css
src/css/components/po-accordion/po-accordion-manager.css
src/css/components/po-breadcrumb/po-breadcrumb.css
src/css/components/po-button-group/po-button-group.css
src/css/components/po-button/po-button.css
src/css/components/po-calendar/po-calendar.css
src/css/components/po-disclaimer/po-disclaimer.css
src/css/components/po-dropdown/po-dropdown.css
src/css/components/po-field/po-checkbox/po-checkbox.css
src/css/components/po-field/po-datepicker-range/po-datepicker-range.css
src/css/components/po-field/po-input/po-input.css
src/css/components/po-field/po-radio/po-radio.css
src/css/components/po-field/po-select/po-select.css
src/css/components/po-field/po-switch/po-switch.css
src/css/components/po-field/po-textarea/po-textarea.css
src/css/components/po-link/po-link.css
src/css/components/po-listbox/po-item-list/po-item-list.css
src/css/components/po-menu/po-menu-filter/po-menu-filter.css
src/css/components/po-menu/po-menu-item/po-menu-item.css
src/css/components/po-menu/po-menu.css
src/css/components/po-search/po-search.css
src/css/components/po-tag/po-tag.css
src/css/components/po-widget/po-widget.css
src/css/themes/po-theme-default.css

fixes DTHFUI-7787
zip para teste: 
[app.zip](https://github.com/po-ui/po-style/files/12917851/app.zip)
*testar theme-totvs e po-ui
theme: https://github.com/totvs/po-theme-totvs/pull/262

refactor(inputs): altera estilo do tema

---

CHANGELOG.md
package.json

build: release v16.4.0

---

CHANGELOG.md
package.json

build: release v16.4.1

---

src/css/components/po-field/po-field-icon/po-field-icon.css
src/css/components/po-field/po-input/po-input.css
src/css/components/po-field/po-multiselect/po-multiselect.css
src/css/components/po-listbox/po-listbox.css
src/css/themes/po-theme-default.css

Implementar as definições do handoff do multiselect no PoMultiselect.
Fixes DTHFUI-7684

feat(multiselect): implementa as definições do AnimaliaDS

---

CHANGELOG.md
package.json

build: release v16.5.0

---

CHANGELOG.md
package.json

build: release v16.6.0

---

src/css/components/index.css
src/css/components/po-loading/po-loading.css
src/css/components/po-overlay/index.css
src/css/components/po-overlay/po-overlay.css
src/css/themes/po-theme-default.css

feat(loading-overlay): novo componente interno po-overlay e implementações de definições de estilo do AnimaliaDS
DTHFUI-7502

feat(loading-overlay): novo componente interno po-overlay e implementações do AnimaliaDS

---

src/css/components/po-button/po-button.css
src/css/components/po-loading/po-loading-icon/po-loading-icon.css
src/css/components/po-menu/po-menu-filter/po-menu-filter.css
src/css/themes/po-theme-default.css

feat(loading-icon): implementa definições do AnimaliaDS

---

src/css/components/po-accordion/po-accordion-item-header.css
src/css/components/po-accordion/po-accordion-manager.css

Ajusta customização do icone do accordion em seus estados.
fixes DTHFUI-7944

fix(accordion): ajusta customização via tokens

---

CHANGELOG.md
package.json

build: release v16.7.0

---

CHANGELOG.md
package.json

build: release v16.10.0

---

src/css/components/po-badge/po-badge.css
src/css/themes/po-theme-default.css

implementa definições do AnimaliaDS
Fixes DTHFUI-7933

feat(badge): implementa definições do AnimaliaDS

---

src/css/services/po-notification/po-toaster/po-toaster.css
src/css/themes/po-theme-default.css

**Testar com os tokens**
/* Novos tokens */
```
po-toaster {
--border-radius: var(--border-radius-md);
--color-icon: var(--color-neutral-light-00);
--shadow: var(--shadow-lg);
--color-success: var(--color-feedback-positive-base);
--background-success: var(--color-feedback-positive-lightest);
--border-color-success: var(--color-feedback-positive-lighter);
--color-error: var(--color-feedback-negative-base);
--background-error: var(--color-feedback-negative-lightest);
--border-color-error: var(--color-feedback-negative-lighter);
--color-warning: var(--color-feedback-warning-base);
--color-icon-warning: var(--color-neutral-dark-90);
--background-warning: var(--color-feedback-warning-lightest);
--border-color-warning: var(--color-feedback-warning-lighter);
--color-info: …
```

feat(toaster): implementa definições do AnimaliaDS

---

CHANGELOG.md
package.json

build: release v16.12.0

---

src/css/components/po-calendar/po-calendar.css

- Simulação: :building_construction:
[app.zip](https://github.com/po-ui/po-style/files/13992642/app.zip)

fix(calendar): ajusta `po-calendar` dentro do `po-table`

---

src/css/components/po-table/po-table.css

Ajusta propriedade width das colunas
Fixes DTHFUI-7754

fix(table): ajusta propriedade width

---

CHANGELOG.md
package.json

build: release v16.13.0

---

src/css/themes/po-theme-default.css

refactor(fields): deprecia variaveis de estilo legacy

---

CHANGELOG.md
package.json

build: release v16.14.0

---

src/css/components/po-page/po-page-default/po-page-default.html
src/css/components/po-page/po-page-detail/po-page-detail.html
src/css/components/po-page/po-page-edit/po-page-edit.html
src/css/components/po-page/po-page-header/po-page-header.css
src/css/components/po-page/po-page-header/po-page-header.html
src/css/components/po-page/po-page-list/po-page-list.css
src/css/components/po-page/po-page-list/po-page-list.html
src/css/themes/po-theme-default.css

Implementação da propriedade de subtitulo
fixes DTHFUI-8292

feat(page-default): inclusão do subtitle

---

CHANGELOG.md
package.json

build: release v16.15.0

---

src/css/components/po-table/po-table-column-manager/po-table-column-manager.css
src/css/services/po-notification/po-toaster/po-toaster.css

refactor(components): remove propriedades depreciadas

refactor(components): remove propriedades depreciadas

---

CHANGELOG.md
package.json

build: release v17.0.0-next.0

---

src/css/components/po-info/po-info.css
src/css/components/po-tag/po-tag.css
src/css/themes/po-theme-default.css

feat(info): implementa definições de espaçamento

feat(info): implementa definições de espaçamento

---

docs/guides/theme-customization.md

docs(customizacao): ajusta guia de customização

docs(customizacao): ajusta guia de customização

---

.github/workflows/pr_ci.yml
.github/workflows/publish_style_cd-beta.yml
scripts/update-version.js

Ajusta a publicação na tag @beta do NPM
Fixes DTHFUI-8276

ci: ajusta a publicacao da tag @beta

---

.github/workflows/pr_ci.yml

feat(ci): realiza integração com o discord

---

CHANGELOG.md
package.json

build: release v17.1.1

---

CHANGELOG.md
package.json

build: release v17.2.0

---

CHANGELOG.md
package.json

build: release v17.3.0

---

CHANGELOG.md
package.json

build: release v17.4.0

---

CHANGELOG.md
package.json

build: release v17.5.0

---

src/css/components/po-search/po-search.css

Implementação da propriedade 't-show-listbox'.
Com essa propriedade ativa, sempre ira mostrar uma listbox das opções informadas, quando houver mudança no input. ela também obedece a regra do filterKeys
fixes DTHFUI-7812

feat(search): inclusão do listbox ao fazer o search

---

CHANGELOG.md
package.json
src/css/components/index.css
src/css/components/po-dynamic/index.css
src/css/components/po-dynamic/po-dynamic.css
src/css/components/po-search/po-search.css
src/css/themes/po-theme-default.css

build: release v17.6.0

---

CHANGELOG.md
package.json

build: release v17.7.0

---

src/css/components/po-field/po-combo/po-combo.css
src/css/themes/po-theme-default.css

Adicionado po-combo e po-multiselect no THF-GRID
fixes DTHFUI-8652

feat(grid): adiciona `po-combo` e `po-multiselect` na edição em linha

---

CHANGELOG.md
package.json

build: release v17.9.0

---

CHANGELOG.md
package.json

release v17.10.0

---

src/css/components/po-table/po-table.css

feat(table): permite mais visão de itens e colunas

feat(table): Permite maior visibilidade de itens e colunas

---

src/css/components/po-menu/po-menu.css

Altera o estilo do scroll no componente po-menu
DTHFUI-8894
app: 
[app.zip](https://github.com/po-ui/po-style/files/15355696/app.zip)

feat(menu): altera estilo do scroll

---

src/css/components/po-dropdown/po-dropdown.css
src/css/components/po-search/po-search.css
src/css/themes/po-theme-default.css

Adição da propriedade `p-filter-select`, a propriedade define os tipos de filtros (p-filter-keys) a serem aplicados na busca ou lista do componente (p-items).
fixes DTHFUI-8644

feat(search): inclusão da propriedade se filterSelect

---

src/css/components/index.css
src/css/components/po-clean/index.css
src/css/components/po-clean/po-clean.css
src/css/components/po-field/po-combo/po-combo.css
src/css/components/po-field/po-input/po-input.css
src/css/components/po-search/po-search.css

Atualiza o ícone do `po-clean` definido pelo animália DS
Fixes DTHDUI-8875

feat(clean): atualiza icone definido pelo animalia

---

CHANGELOG.md
package.json

build: release 17.15.0

---

CHANGELOG.md
package.json

build: release 17.15.1

---

CHANGELOG.md
package.json

build: release 17.15.2

---

src/css/components/po-table/po-table.css

Ajusta cursor na coluna draggable  com a fonte Phosphor
Fixes DTHFUI-9148

fix(table): ajusta cursor na coluna draggable

---

src/css/components/po-tabs/po-tab-button/po-tab-button.css
src/css/themes/po-global-tokens.css

Corrige a cor de fundo do tabs para --color-transparent possibilitar uma visibilidade melhor em diferentes temas
fixes DTHFUI-8913

fix(tabs): corrige cor de fundo

---

CHANGELOG.md
package.json

build: release 17.17.0

---

CHANGELOG.md
package.json

build: release 17.17.1

---

src/css/components/po-tabs/po-tab-dropdown/po-tab-dropdown.css

Corrige o posicionamento do `po-listbox` possibilitando uma visibilidade melhor dos itens.
fixes DTHFUI-8917

fix(tab-dropdown): corrige posicionamento

---

CHANGELOG.md
package.json

build: release v17.18.0

---

CHANGELOG.md
package.json

build: release 17.18.1

---

CHANGELOG.md
package.json

build: release v17.19.0

---

CHANGELOG.md
package.json

build: release 18.0.0-next.0

---

CHANGELOG.md
package.json

build: release 17.20.0

---

src/css/commons/po-color/po-color.css
src/css/components/po-accordion/po-accordion-item-header.css
src/css/components/po-breadcrumb/po-breadcrumb-dropdown.css
src/css/components/po-breadcrumb/po-breadcrumb.css
src/css/components/po-button-group/po-button-group.css
src/css/components/po-dropdown/po-dropdown.css
src/css/components/po-field/po-checkbox/po-checkbox.css
src/css/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.css
src/css/components/po-field/po-field-icon/po-field-icon.css
src/css/components/po-field/po-input/po-input.css
src/css/components/po-field/po-lookup/po-lookup.css
src/css/components/po-grid/po-grid-cell-action.css
src/css/components/po-grid/po-grid-cell-content.css
src/css/components/po-grid/po-grid-head.css
src/css/components/po-loading-overlay/po-loading-overlay.css
src/css/components/po-loading/po-loading-icon/po-loading-icon.css
src/css/components/po-loading/po-loading.css
src/css/components/po-menu/po-menu-filter/po-menu-filter.css
src/css/components/po-menu/po-menu-item/po-menu-item.css
src/css/components/po-menu/po-menu.css
src/css/components/po-modal/po-modal.css
src/css/components/po-page/po-page-header/po-page-header.css
src/css/components/po-popup/po-popup.css
src/css/components/po-progress/po-progress-bar/po-progress-bar.css
src/css/components/po-progress/po-progress.css
src/css/components/po-table/po-table.css
src/css/components/po-tabs/po-tab-button/po-tab-button.css
src/css/services/po-notification/po-toaster/po-toaster.css
src/css/themes/po-theme-default.css

refactor(components): remove variáveis depreciadas
removido tokens que estavam marcados como depreciados.
Fixes DTHFUI-9125
BREAKING CHANGE: removido tokens que estavam marcados como depreciados.
Removido tokens que estavam marcados como depreciados.

refactor(components): remove deprecated variables

---

CHANGELOG.md
package.json

build: release 17.21.0

---

CHANGELOG.md
package.json

build: release v17.22.0 - DTHFUI-9626

build: release v17.22.0 - DTHFUI-9626

---

CHANGELOG.md
package.json

build: release 18.2.0

---

src/css/commons/po-common.css
src/css/commons/po-font/po-font.css
src/css/commons/po-shadow/po-shadow.css
src/css/components/po-gauge/po-gauge.css
src/css/components/po-grid/po-grid-cell-content.css
src/css/components/po-list-view/po-list-view.css
src/css/components/po-page/po-page-blocked-user/po-page-blocked-user.css
src/css/components/po-page/po-page-change-password/po-page-change-password.css
src/css/components/po-table/po-table.css
src/css/themes/po-theme-default.css

docs(portal): insere tema dark no portal

---

CHANGELOG.md
package.json

build: release 18.7.0

---

src/css/components/po-stepper/po-stepper.css
src/css/themes/po-theme-default.css

**PO-STEPPER**
**DTHFUI-9714**
**PR Checklist [Revisor]**
Após as implementações do animalia, os steps passaram a ser alinhados à esquerda no modo horizontal e ao topo no modo vertical.
Adiciona propriedade p-align-center que permite o alinhamento centralizado dos steps em ambas as orientações.

feat(stepper): adiciona propriedade p-align-center

---

CHANGELOG.md
package.json

build: release 17.26.1

---

CHANGELOG.md
package.json

build: release 18.8.0

---

CHANGELOG.md
package.json

build: release 17.26.2

---

CHANGELOG.md
package.json

build: release 18.9.0

---

src/css/components/po-page/po-page-slide/po-page-slide.css
src/css/themes/po-global-tokens.css
src/css/themes/po-theme-default.css

Implementa definições do animaliaDS no page-slide
fixes DTHFUI-9873

feat(page-slide): implementa definições do animalia-DS

---

CHANGELOG.md
package.json

build: release 17.26.4

---

src/css/components/po-accordion/po-accordion-item-header.css
src/css/components/po-accordion/po-accordion-manager.css

Corrige texto estourando a tela no accordion
fixes DTHFUI-9636

fix(accordion): corrige texto grande no componente

---

.gitignore
src/css/components/po-container/po-container.css
src/css/components/po-dynamic/po-dynamic.css
src/css/themes/po-theme-default.css

Adicionado propriedade `p-title` e tokens customizados para o titulo em `po-container`
fixes DTHFUI-9918

feat(container): adicionado titulo

---

src/css/components/po-accordion/po-accordion-item-header.css
src/css/components/po-accordion/po-accordion-manager.css

Corrige texto estourando a tela no accordion
fixes DTHFUI-9636

fix(accordion): corrige texto grande no componente (17)

---

src/css/components/po-field/po-lookup/po-lookup.css
src/css/themes/po-theme-default.css

DTHFUI-9693
Implementa definições Animalia no po-lookup:
- Recebe comportamento semelhante do modo trigger do po-search onde possibilita navegar pelo input, realizar consulta, apagar o(s) valor(es) e abrir a modal, pelo teclado.
- Mantém o estilo e a customização animalia;

feat(lookup): implementa definições animalia-DS

---

package.json

corrige vulnerabilidades apontadas pelo Github atualizando versão do xml2js
fixes DTHFUI-10148

fix: corrige vulnerabilidade da biblioteca xml2js

---

CHANGELOG.md
package.json

build: release 17.26.7

---

CHANGELOG.md
package.json

build: release 18.14.0

---

src/css/components/po-field/po-combo/po-combo.css
src/css/components/po-field/po-select/po-select.css
src/css/themes/po-theme-default.css

- Implementação das cores especificadas no handoff do Figma para os componentes po-combo e po-select.
chevron-down/DTHFUI-9679

fix(combo/select): ajusta cores do chevron-down conforme AnimaliaDS

---

CHANGELOG.md
package.json

build: release 18.17.0

---

CHANGELOG.md
package.json

build: release 18.20.0

---

src/css/components/po-stepper/po-stepper.css

Cria propriedade p-disable-click para desabilitar o clique no step
DTHFUI-9924

feat(stepper): cria a propriedade p-disable-click

---

src/css/components/po-upload/po-upload.css

Adiciona suporte a ações customizadas no componente `po-progress` por meio das novas propriedades `p-custom-action` e `p-custom-action-click`. Permite configurar ícone, label, tipo, visibilidade e estado de desabilitado do botão customizado. Integra a funcionalidade aos componentes `po-upload` e `po-dynamic-form`, garantindo que a propriedade `p-custom-action-click` retorne o arquivo associado à ação.
Fixes DTHFUI-10272

feat(progress): adiciona suporte a ações customizadas

---

CHANGELOG.md
package.json

build: release 17.26.11

---

CHANGELOG.md
package.json

build: release 19.0.0-rc.0

---

src/css/components/po-accordion/po-accordion-item-header.css

Qual o comportamento atual?
A tag está desalinhada e fora do padrão definido pela AnimaliaDS.
Qual o novo comportamento?
A tag está alinhada e dentro do padrão definido pela AnimaliaDS.
fixes DTHFUI-10166

fix(accordion): alinha posicionamento da tag em relação ao titulo

---

CHANGELOG.md
package.json

build: release 17.26.12

---

src/css/components/po-field/po-checkbox-group/po-checkbox-group.css
src/css/components/po-field/po-field-container/po-field-container-bottom/po-field-container-bottom.css

Implementa  help adicional ao `p-help`, permitindo exibir um tooltip ou disparar um evento.
fixes DTHFUI-10443

feat(components): implementa help adicional ao p-help

---

CHANGELOG.md
package.json

build: release 19.1.0

---

CHANGELOG.md
package.json

build: release 17.26.13

---

CHANGELOG.md
package.json

build: release 19.2.0

---

CHANGELOG.md
package.json

build: release v17.26.17

---

CHANGELOG.md
package.json

build: release 19.5.0

---

CHANGELOG.md
package.json

build: release 17.26.18

---

CHANGELOG.md
package.json

build: release 19.5.1

---

src/css/components/po-field/po-switch/po-switch.css

Define espaçamento padrão para o componente po-field-container-bottom dentro do po-switch

feat(switch): adiciona mensagem de erro de invalid ou required

---

src/css/components/po-field/po-select/po-select.css

fix(select): corrige seletor para campos inválidos

---

src/css/themes/po-theme-default.css

Remove variável de cor não utilizada
- `color-chart-legend-wrapper-scrollbar`.
- `color-chart-line-point-fill`.
- `color-gauge-description-bottom-focus`.
- `color-gauge-legend-scrollbar`.
- `color-gauge-legend-text`.
- `color-gauge-pointer-color`.
Fixes DTHFUI-11334
BREAKING CHANGE: remove variáveis de customização de cores
Remove variáveis para compatibilidade com AnimaliaDS e melhorias de acessibilidade, não sendo mais possível a customização.
- `color-chart-legend-wrapper-scrollbar`
- `color-chart-line-point-fill`
- `color-gauge-description-bottom-focus`
- `color-gauge-legend-scrollbar`
- `color-gauge-legend-text`
- `color-gauge-pointer-color`

refactor(chart): remove variáveis não utilizadas

---

src/css/components/po-field/po-multiselect/po-multiselect.css

Adiciona height e max-height de 2.75rem para o input do AAA; 
Adiciona height e max-height de 2rem para o input do AA;
Fixes: DTHFUI-11212

fix(multiselect): adiciona max-height ao input

---

CHANGELOG.md
package.json

build: release 19.21.0

---

src/css/components/po-search/po-search.css
src/css/themes/po-theme-default.css

Novo modo manual que não executa busca automaticamente.
fixes DTHFUI-11133
```
po-search {
/* Default */
--border-radius: 1rem;
--font-size: 1.5rem;
--font-family: 'PT Serif', serif;
--color: #ffd700;
--text-color: #ffd700;
--border-color: #ffd700;
/* Placeholder */
--text-color-placeholder: #ffc300;
/* Hover */
--color-hover: #ffc300;
--background-hover: #fff8dc;
/* Focused */
--color-focused: #ffb700;
--outline-color-focused: #ffb700;
/* Disabled */
--color-disabled: #b8860b;
--background-disabled: #fafad2;
/* Icon */
--color-icon: #ffd700;
--color-icon-read: #ffecb3;
/* Clear & Controls */
--color-clear: #ffd700;
--color-controls: #ffd700;
}
```

feat(search): adiciona modo locate ao p-search-type

---

CHANGELOG.md
package.json

build: release 19.26.0

---

src/css/commons/po-grid-system/po-grid-system.css
src/css/components/index.css
src/css/components/po-field/po-checkbox/po-checkbox.css
src/css/components/po-field/po-datepicker/po-datepicker.css
src/css/components/po-field/po-field-container/po-field-container.css
src/css/components/po-helper/index.css
src/css/components/po-helper/po-helper.css
src/css/components/po-helper/po-helper.html
src/css/components/po-label/po-label.css
src/css/themes/po-global-tokens.css
src/css/themes/po-theme-default.css

Implementa o componente de ajuda (po-helper) que fornece funcionalidades de orientação ao usuário dentro da aplicação, levando a informação através do PO-Popover. Implementa definições de acessibilidade no PO-Label para suporte a tooltips e campos obrigatórios.
Fixes DTHFUI-11065

feat(helper): implementa novo componente de ajuda
